Nivel 1

1. Calculadora de l'índex de massa corporal

Escriu una funció que calculi l'IMC ingressat per l'usuari/ària, és a dir, qui ho executi haurà d'ingressar aquestes dades.
La funció ha de classificar el resultat en les seves respectives categories.

Consell: Intenta validar les dades prèviament, perquè enviï un missatge d’advertència si les dades introduïdes per l’usuari/a no estan en el format adequat o no pren valors raonables.

In [1]:
# Definimos la función
def calc_imc(peso, altura):
    return round(peso / (altura ** 2),2)

In [2]:
# Solicitar peso y altura al usuario

peso = (input("Ingresa tu peso en kilogramos: "))
altura = (input("Ingresa tu altura en metros:"))

# Validar que los valores no estén vacíos y sean numéricos

if not peso or not altura:
        print("Error: Debes ingresar valores para peso y altura")
else:
    try: 
            peso_float = float(peso)
            altura_float= float(altura)
    except ValueError:
            print("Error: Ingresa valores numéricos válidos para peso y altura")
 

# Llamamos a la función
imc_total = calc_imc(peso_float, altura_float)

#Categorizamos los resultados del IMC

if imc_total <= 18.5:
    print(f"Tu IMC es: {imc_total}", "y se corresponde con un bajo peso")
elif imc_total > 18.5 and imc_total <= 24.9:
    print(f"Tu IMC es: {imc_total}", "y se corresponde con un peso normal")
elif imc_total > 24.9 and imc_total < 29.9:
    print(f"Tu IMC es: {imc_total}", "y se corresponde con un sobrepeso")
else:
    print(f"Tu IMC es: {imc_total}", "y se corresponde con obesidad")

Tu IMC es: 24.07 y se corresponde con un peso normal

Para la función de calculo del IMC he utilizado el manejo de excepciones de error, mediante la declaración "try/except". Con esto se busca evitar posibles errores de valores de input, por parte del usuario. Luego mediante condicionales (if/elif) se han categorizado los resultados de la función, de acuerdo a los valores preestablecidos.

---------------------------------------------------------------------------------------------------------------------

2. Convertidor de temperatures

Existeixen diverses unitats de temperatura utilitzades en diferents contextos i regions. Les més comunes són Celsius (°C), Fahrenheit (°F) i Kelvin (K). També existeixen altres unitats com Rankine (°Ra) i Réaumur (°Re).

Selecciona almenys 2 conversors, de tal manera que en introduir una temperatura retorni, com a mínim, dues conversions, de manera que es puguin guardar (recorda que un print() no es pot guardar mai).

Consell: Intenta validar les dades prèviament, perquè enviï un missatge d’advertència si les dades introduides per l’usuari/a no estan en el format adequat.

(EXTRA): Pensa una manera d’emmagatzemar totes les possibles conversions en un sol objecte (Llista? Diccionari? DataFrame?) en comptes d’escriure molts if else en funció de la temperatura d’origen i la temperatura de destí.

In [2]:
#Definimos las funciones para cada tipo de conversión de unidad de temperatura
def cel_a_kelvin(valor):
    return valor + 273.15

def cel_a_far(valor):
    return (valor * 9/5) + 32

def kelvin_a_cel(valor):
    return valor - 273.15

def kelvin_a_far(valor):
    return (valor - 273.15) * 9/5 + 32

def far_a_cel(valor):
    return (valor - 32) * 5/9

def far_a_kel(valor):
    return (valor - 32) * 5/9 + 273.15

# Si las unidades son las mismas, no se hace nada
def idem(valor):
    return valor

In [3]:
#Creamos un diccionario con las funciones de conversión y un DataFrame que funcione como matriz de las operaciones

import pandas as pd

# Diccionario de funciones de conversión
operaciones = {
    'CelaK': cel_a_kelvin,
    'CelaF': cel_a_far,
    'KaCel': kelvin_a_cel,
    'KaFar': kelvin_a_far,
    'FaCel': far_a_cel,
    'FaKel': far_a_kel,
    'Idem': idem, # Para el caso de misma unidad
}

# DataFrame para mapear las operaciones
df = pd.DataFrame(
    [
        ['Idem', 'CelaK', 'CelaF'],
        ['KaCel', 'Idem', 'KaFar'],
        ['FaCel', 'FaKel', 'Idem']
    ],
    index=['CELSIUS', 'KELVIN', 'FAHRENHEIT'],
    columns=['CELSIUS', 'KELVIN', 'FAHRENHEIT']
)

df

           CELSIUS KELVIN FAHRENHEIT
CELSIUS       Idem  CelaK      CelaF
KELVIN       KaCel   Idem      KaFar
FAHRENHEIT   FaCel  FaKel       Idem

In [ ]:
#Creamos la función de conversor con los argumentos de entrada

def conversor_temp(u_origen, u_destino, valor, df=df):
    """
    Convierte un valor de temperatura de una unidad a otra.

    Argumentos:
        u_origen (str): Unidad de temperatura de origen (ej. 'Celsius').
        u_destino (str): Unidad de temperatura de destino (ej. 'Kelvin').
        valor (float): El valor numérico a convertir.
        df (pd.DataFrame): DataFrame que mapea las operaciones.
    
    Return:
        float: El valor de la temperatura convertido.
    """
    # Normalizar las unidades a mayúsculas
    u_origen = u_origen.upper()
    u_destino = u_destino.upper()

    # Obtener el nombre de la operación del DataFrame
    nombre_operacion = df.loc[u_origen, u_destino]
    
    # Buscar la función de conversión en el diccionario 'operaciones'
    funcion_conversion = operaciones[nombre_operacion]
    
    # Ejecutar la función con el valor de entrada y devolver el resultado
    return funcion_conversion(float(valor))

temp_celsius = 25
temp_kelvin = conversor_temp('Celsius', 'Kelvin', temp_celsius)
print(f"La temperatura de {temp_celsius}°C es {temp_kelvin}K.")

temp_far = conversor_temp('Kelvin', 'Fahrenheit', temp_kelvin)
print(f"La temperatura de 298.15K es {temp_far}°F.")

temp_c_a_f = conversor_temp('Celsius', 'Fahrenheit', temp_far)
print(f"La temperatura de 100°C es {temp_c_a_f}°F.")

temp_kel_a_cel = conversor_temp('Kelvin', 'Celsius', temp_c_a_f)
print(f"La temperatura de 0K es {temp_kel_a_cel}°C.")

La temperatura de 25°C es 298.15K.
La temperatura de 298.15K es 77.0°F.
La temperatura de 100°C es 170.6°F.
La temperatura de 0K es -102.54999999999998°C.

In [ ]:
#Creamos una lista vacía para almacenar las unidades y los valores de la conversión 
#Creamos un bucle para iterar por cada una de las posibles opciones

lista_medidas = []
finalizar = True

# Unidades válidas
unidades_validas = ['CELSIUS', 'KELVIN', 'FAHRENHEIT']

while finalizar:
    #Solicitamos los datos a convertir al usuario 
    unid1 = input("Ingrese la unidad de temperatura de origen: (ej. 'Celsius')").strip().upper()
    unid2 = input("Ingrese la unidad de la temperatura destino: (ej. 'Kelvin') ").strip().upper()
    temp = input("Ingrese el valor numérico a convertir: ")

    # Validación de datos
    if not unid1 or not unid2 or not temp:
        print("Debes ingresar el nombre correcto de la unidad de medida y el valor a convertir")
        continue
    if unid1 not in unidades_validas or unid2 not in unidades_validas:
        print(f"Unidades no válidas. Las opciones son: {', '.join(unidades_validas)}")
        continue
    try:
        temp_float = float(temp)
    except ValueError:
        print("El valor de temperatura debe ser numérico.")
        continue

    # Realizar la conversión
    operacion = conversor_temp(unid1, unid2, temp_float)
    lista_medidas.append({'origen': unid1, 'destino': unid2, 'valor': temp_float, 'resultado': operacion})

    continuar = input("¿Quiere convertir la temperatura a alguna otra unidad? (SI/NO): ")
    if continuar.strip().upper() == "NO":
        finalizar = False

lista_medidas

[{'origen': 'CELSIUS',
  'destino': 'KELVIN',
  'valor': 30.0,
  'resultado': 303.15}]

Aquí también se ha utilizado el manejo de excepciones de error, mediante try/except, para posibles errores de valor, al input de los datos por parte del usuario. Tambíen mediante la función "strip" se eliminan caracteres no deseados en el input, y con "upper" convertimos todos los caracteres del "string" a mayúsculas.

---------------------------------------------------------------------------------------------------------------------

3. Comptador de paraules d'un text.

Escriu una funció que donat un text, mostri les vegades que apareix cada paraula. Intenta que es gestionin totes les casuístiques possibles que facin que el programa no funcioni correctament.

(EXTRA): Quina és la llargada mitjana de les paraules del text que has escrit? “Hola com va?” hauria de retornar (4+3+2) / 3 = 3

In [ ]:
texto = "Hola, mundo de Python"
def contar_palabras_unicas(texto): #contar_palabras(cadena): Define una función que toma un texto como argumento.
    palabras = texto.lower().split() #divide el texto en cadenas y convierte los caractéres a minúsculas
    palabras_unicas = set(palabras) #almacena la cantidad de palabras en un conjunto
    contador = 0 #contador = 0: Inicializa un contador a 0. Este contador almacenará el número de caracteres.
    for _ in palabras_unicas: #for _ in cadena:: Itera sobre cada carácter de la cadena. El carácter actual no se necesita, por lo que se usa _ como variable del bucle.
        contador += 1 #contador += 1: En cada iteración, incrementa el contador en 1.
    return contador #return contador: Devuelve el valor final del contador, que representa el número de caracteres en la cadena
              
num_palabras_unicas=contar_palabras_unicas(texto)
print(f"La frase '{texto}', tiene {num_palabras_unicas} palabras unicas")

#EXTRA =
texto = "Hola, mundo de Python"
def contar_sin_espacios_y_comas(texto):
    frase_modificada = texto.replace(" ", "").replace(",", "")
    return len(frase_modificada)


num_letras_frase=contar_sin_espacios_y_comas(texto)
print(f"La frase '{texto}', tiene {num_letras_frase} letras")

media_palabras = num_letras_frase/num_palabras_unicas
print((f"La longitud media de las palabras en la frase:'{texto}', es de {round(media_palabras)} letras"))

La frase 'Hola, mundo de Python', tiene 4 palabras unicas
La frase 'Hola, mundo de Python', tiene 17 letras
La longitud media de las palabras en la frase:'Hola, mundo de Python', es de 4 letras

Se han creado dos funciones, la primera donde se itera mediante un bucle for, por cada caracter del "string" y se almacenan la cantidad en un set, para diferenciar la cantidad de palabras en el texto. La segunda función complementaria, toma el mismo texto como argumento, y reemplaza los signos de puntuación para obtener la longitud correcta de caracteres en el texto. Por último, la longitud media de palabras en la frase, se obtiene mediante la operación de dividir el número de letras por el total de palabras del texto proporcionado.

---------------------------------------------------------------------------------------------------------------------

4. Diccionari invers (amb possibilitat de duplicats)

Resulta que el client té una enquesta molt antiga que s'emmagatzema en un diccionari i els resultats els necessita al revés, és a dir, intercanviant les claus i els valors. Els valors i claus en el diccionari original són únics; si aquest no és el cas, la funció hauria d'imprimir un missatge d'advertiment, juntament amb una llista amb els valors associats a la clau repetida.

In [ ]:
"""
dictionary={'a':1,'b':2,'c':3}
reverse_dictionary={1:'a',2:'b',3:'c'}
dictionary_duplicate={'x':'apple', 'y':'banana','z':'banana'}
reverse_dictionary2={'apple':'x','banana':['y','z']}
"""
d = {'x' : 4, 'y' : 2, 'z' : 5}

#Invertir diccionario con valores únicos
inverted_dict = {value: key for key, value in d.items()}


dict_duplicate= {'a': 'fire', 'b': 'ice', 'c': 'fire', 'd': 'water'}

# Invertir diccionario con valores duplicados
inverted_dict_dup = {}

def invertir_dup(diccionario):
	for key, value in diccionario.items(): #bucle para iterar por cada key, value y los retorna como tuplas en una lista
		if value in inverted_dict_dup: #evalua si el valor está incluido en el diccionario vacio
			inverted_dict_dup[value].append(key) #en el caso que si, adiciona al valor la llave correspondiente
			print("Dicccionario con valores duplicados")
		else:
			inverted_dict_dup[value] = [key] #en el caso que el valor no esté duplicado en el diccionario
	return inverted_dict_dup
			
invertir_dup(dict_duplicate)

Dicccionario con valores duplicados

{'fire': ['a', 'c'], 'ice': ['b'], 'water': ['d']}

Se crea una función, que toma como argumento un diccionario. Para este caso en particular, se emplean dos ejemplos. Un diccionario sin y con valores duplicados. La función a través de un bucle for, itera por cada llave y valor del diccionario, y mediante la función items, separa cada par en una tupla, para luego poder agregarlos al nuevo diccionario que se ha creado, para alojar los valores duplicados junto a su llave correspondiente.

---------------------------------------------------------------------------------------------------------------------

Nivel 2

1. Comptador i endreçador de paraules d'un text.

El client va quedar content amb el comptador de paraules, però ara vol llegir arxius TXT i que calculi la freqüència de cada paraula ordenades dins de les entrades habituals del diccionari segons la lletra amb la qual comencen, és a dir, les claus han d'anar de la A a la Z i dins de la A hem d'anar de la A la Z

In [ ]:
file=(r"C:\Users\jprom\Desktop\IT Academy\Python\Data Analytics\Sprint 9\tu me quieres blanca.txt")

#Creamos una función para almacenar en una lista todas las palabras del archivo de texto importado
def lista_palabras_archivo(filename):
    #Utilizamos el método with open para que el archivo importado se cierre, luego de su uso
    with open(filename, "r", encoding="utf-8") as f:
        palabras_extraidas = []
        for line in f:
            #Dividimos cada linea de la lista en los elementos/palabras que la componen y convertimos a minúsculas
            lista_palabras = line.lower().split()
            #Con la función extend fusionamos los diferentes elementos iterables de cada linea del texto, en una lista
            palabras_extraidas.extend(lista_palabras)
        return palabras_extraidas

lista_palabras_txt= lista_palabras_archivo(file)
print(lista_palabras_txt)

['tú', 'me', 'quieres', 'alba,', 'me', 'quieres', 'de', 'espumas,', 'me', 'quieres', 'de', 'nácar.', 'que', 'sea', 'azucena', 'sobre', 'todas,', 'casta.', 'de', 'perfume', 'tenue.', 'corola', 'cerrada', '.', 'ni', 'un', 'rayo', 'de', 'luna', 'filtrado', 'me', 'haya.', 'ni', 'una', 'margarita', 'se', 'diga', 'mi', 'hermana.', 'tú', 'me', 'quieres', 'nívea,', 'tú', 'me', 'quieres', 'blanca,', 'tú', 'me', 'quieres', 'alba.', 'tú', 'que', 'hubiste', 'todas', 'las', 'copas', 'a', 'mano,', 'de', 'frutos', 'y', 'mieles', 'los', 'labios', 'morados.', 'tú', 'que', 'en', 'el', 'banquete', 'cubierto', 'de', 'pámpanos', 'dejaste', 'las', 'carnes', 'festejando', 'a', 'baco.', 'tú', 'que', 'en', 'los', 'jardines', 'negros', 'del', 'engaño', 'vestido', 'de', 'rojo', 'corriste', 'al', 'estrago.', 'tú', 'que', 'el', 'esqueleto', 'conservas', 'intacto', 'no', 'sé', 'todavía', 'por', 'cuáles', 'milagros,', 'me', 'pretendes', 'blanca', '(dios', 'te', 'lo', 'perdone),', 'me', 'pretendes', 'casta', '(dios', 'te', 'lo', 'perdone),', '¡me', 'pretendes', 'alba!', 'huye', 'hacia', 'los', 'bosques,', 'vete', 'a', 'la', 'montaña;', 'límpiate', 'la', 'boca;', 'vive', 'en', 'las', 'cabañas;', 'toca', 'con', 'las', 'manos', 'la', 'tierra', 'mojada;', 'alimenta', 'el', 'cuerpo', 'con', 'raíz', 'amarga;', 'bebe', 'de', 'las', 'rocas;', 'duerme', 'sobre', 'escarcha;', 'renueva', 'tejidos', 'con', 'salitre', 'y', 'agua:', 'habla', 'con', 'los', 'pájaros', 'y', 'lévate', 'al', 'alba.', 'y', 'cuando', 'las', 'carnes', 'te', 'sean', 'tornadas,', 'y', 'cuando', 'hayas', 'puesto', 'en', 'ellas', 'el', 'alma', 'que', 'por', 'las', 'alcobas', 'se', 'quedó', 'enredada,', 'entonces,', 'buen', 'hombre,', 'preténdeme', 'blanca,', 'preténdeme', 'nívea,', 'preténdeme', 'casta.']

In [ ]:
#Creamos una nueva función para almacenar en un diccionario las palabras de la lista y cantidad, como key y value
def contar_palabras(lista):
    contador_palabras = {}
    for palabra in lista:
        # Limpia la palabra de comas, puntos, signos, etc. y la convierte a minúsculas
        palabra_limpia = palabra.replace(',', '').replace('.', '').replace('(', '').replace('¡','').lower()
        # Ignora las cadenas vacías que podrían resultar de la limpieza
        if palabra_limpia:
        # Incrementa el conteo de la palabra si ya existe, si no, la inicializa en 1
            if palabra_limpia in contador_palabras:
                contador_palabras[palabra_limpia] += 1
            else:
                contador_palabras[palabra_limpia] = 1
    return contador_palabras

# Llama a la función y muestra el resultado
resultado = contar_palabras(lista_palabras_txt)
print(resultado)

{'tú': 8, 'me': 10, 'quieres': 6, 'alba': 3, 'de': 8, 'espumas': 1, 'nácar': 1, 'que': 6, 'sea': 1, 'azucena': 1, 'sobre': 2, 'todas': 2, 'casta': 3, 'perfume': 1, 'tenue': 1, 'corola': 1, 'cerrada': 1, 'ni': 2, 'un': 1, 'rayo': 1, 'luna': 1, 'filtrado': 1, 'haya': 1, 'una': 1, 'margarita': 1, 'se': 2, 'diga': 1, 'mi': 1, 'hermana': 1, 'nívea': 2, 'blanca': 3, 'hubiste': 1, 'las': 7, 'copas': 1, 'a': 3, 'mano': 1, 'frutos': 1, 'y': 5, 'mieles': 1, 'los': 4, 'labios': 1, 'morados': 1, 'en': 4, 'el': 4, 'banquete': 1, 'cubierto': 1, 'pámpanos': 1, 'dejaste': 1, 'carnes': 2, 'festejando': 1, 'baco': 1, 'jardines': 1, 'negros': 1, 'del': 1, 'engaño': 1, 'vestido': 1, 'rojo': 1, 'corriste': 1, 'al': 2, 'estrago': 1, 'esqueleto': 1, 'conservas': 1, 'intacto': 1, 'no': 1, 'sé': 1, 'todavía': 1, 'por': 2, 'cuáles': 1, 'milagros': 1, 'pretendes': 3, 'dios': 2, 'te': 3, 'lo': 2, 'perdone)': 2, 'alba!': 1, 'huye': 1, 'hacia': 1, 'bosques': 1, 'vete': 1, 'la': 3, 'montaña;': 1, 'límpiate': 1, 'boca;': 1, 'vive': 1, 'cabañas;': 1, 'toca': 1, 'con': 4, 'manos': 1, 'tierra': 1, 'mojada;': 1, 'alimenta': 1, 'cuerpo': 1, 'raíz': 1, 'amarga;': 1, 'bebe': 1, 'rocas;': 1, 'duerme': 1, 'escarcha;': 1, 'renueva': 1, 'tejidos': 1, 'salitre': 1, 'agua:': 1, 'habla': 1, 'pájaros': 1, 'lévate': 1, 'cuando': 2, 'sean': 1, 'tornadas': 1, 'hayas': 1, 'puesto': 1, 'ellas': 1, 'alma': 1, 'alcobas': 1, 'quedó': 1, 'enredada': 1, 'entonces': 1, 'buen': 1, 'hombre': 1, 'preténdeme': 3}

In [22]:
#Creamos una función que toma como parámetro el diccionario con las claves y valores
def indice_palabras(diccionario):
    #Diccionario para alojar las claves como indices
    dic_final = {} 
    #Separamos la clave y valor del diccionario parámetro
    for palabra, cantidad in diccionario.items(): 
        primera_letra = palabra[0] 
        #Condicional para adicionar al diccionario final la primer letra de cada clave
        if primera_letra not in dic_final: 
            dic_final[primera_letra] = {}
        #Asignamos la primera letra y la palabra como claves y la cantidad como valor
        dic_final[primera_letra][palabra] = cantidad 
    return dic_final

resultado_indice = indice_palabras(resultado)
print(resultado_indice)

{'t': {'tú': 8, 'todas': 2, 'tenue': 1, 'todavía': 1, 'te': 3, 'toca': 1, 'tierra': 1, 'tejidos': 1, 'tornadas': 1}, 'm': {'me': 10, 'margarita': 1, 'mi': 1, 'mano': 1, 'mieles': 1, 'morados': 1, 'milagros': 1, 'montaña;': 1, 'manos': 1, 'mojada;': 1}, 'q': {'quieres': 6, 'que': 6, 'quedó': 1}, 'a': {'alba': 3, 'azucena': 1, 'a': 3, 'al': 2, 'alba!': 1, 'alimenta': 1, 'amarga;': 1, 'agua:': 1, 'alma': 1, 'alcobas': 1}, 'd': {'de': 8, 'diga': 1, 'dejaste': 1, 'del': 1, 'dios': 2, 'duerme': 1}, 'e': {'espumas': 1, 'en': 4, 'el': 4, 'engaño': 1, 'estrago': 1, 'esqueleto': 1, 'escarcha;': 1, 'ellas': 1, 'enredada': 1, 'entonces': 1}, 'n': {'nácar': 1, 'ni': 2, 'nívea': 2, 'negros': 1, 'no': 1}, 's': {'sea': 1, 'sobre': 2, 'se': 2, 'sé': 1, 'salitre': 1, 'sean': 1}, 'c': {'casta': 3, 'corola': 1, 'cerrada': 1, 'copas': 1, 'cubierto': 1, 'carnes': 2, 'corriste': 1, 'conservas': 1, 'cuáles': 1, 'cabañas;': 1, 'con': 4, 'cuerpo': 1, 'cuando': 2}, 'p': {'perfume': 1, 'pámpanos': 1, 'por': 2, 'pretendes': 3, 'perdone)': 2, 'pájaros': 1, 'puesto': 1, 'preténdeme': 3}, 'u': {'un': 1, 'una': 1}, 'r': {'rayo': 1, 'rojo': 1, 'raíz': 1, 'rocas;': 1, 'renueva': 1}, 'l': {'luna': 1, 'las': 7, 'los': 4, 'labios': 1, 'lo': 2, 'la': 3, 'límpiate': 1, 'lévate': 1}, 'f': {'filtrado': 1, 'frutos': 1, 'festejando': 1}, 'h': {'haya': 1, 'hermana': 1, 'hubiste': 1, 'huye': 1, 'hacia': 1, 'habla': 1, 'hayas': 1, 'hombre': 1}, 'b': {'blanca': 3, 'banquete': 1, 'baco': 1, 'bosques': 1, 'boca;': 1, 'bebe': 1, 'buen': 1}, 'y': {'y': 5}, 'j': {'jardines': 1}, 'v': {'vestido': 1, 'vete': 1, 'vive': 1}, 'i': {'intacto': 1}}

In [23]:
# Diccionario con un indice como clave, y el resto como valor
diccionario_original = resultado_indice

# Ordenar las claves principales del diccionario proporcionado
claves_ordenadas = sorted(diccionario_original.keys())

# Crear un nuevo diccionario vacío para el resultado
diccionario_ordenado = {}

# Iterar sobre las claves principales ordenadas
for clave in claves_ordenadas:
    # Obtener el sub-diccionario correspondiente
    sub_diccionario = diccionario_original[clave]
    
    # Ordenar las claves del sub-diccionario
    sub_diccionario_ordenado = dict(sorted(sub_diccionario.items()))
    
    # Asignar el sub-diccionario ordenado al nuevo diccionario
    diccionario_ordenado[clave] = sub_diccionario_ordenado

# Imprimir el diccionario resultante
import pprint
pprint.pprint(diccionario_ordenado)

{'a': {'a': 3,
       'agua:': 1,
       'al': 2,
       'alba': 3,
       'alba!': 1,
       'alcobas': 1,
       'alimenta': 1,
       'alma': 1,
       'amarga;': 1,
       'azucena': 1},
 'b': {'baco': 1,
       'banquete': 1,
       'bebe': 1,
       'blanca': 3,
       'boca;': 1,
       'bosques': 1,
       'buen': 1},
 'c': {'cabañas;': 1,
       'carnes': 2,
       'casta': 3,
       'cerrada': 1,
       'con': 4,
       'conservas': 1,
       'copas': 1,
       'corola': 1,
       'corriste': 1,
       'cuando': 2,
       'cubierto': 1,
       'cuerpo': 1,
       'cuáles': 1},
 'd': {'de': 8, 'dejaste': 1, 'del': 1, 'diga': 1, 'dios': 2, 'duerme': 1},
 'e': {'el': 4,
       'ellas': 1,
       'en': 4,
       'engaño': 1,
       'enredada': 1,
       'entonces': 1,
       'escarcha;': 1,
       'espumas': 1,
       'esqueleto': 1,
       'estrago': 1},
 'f': {'festejando': 1, 'filtrado': 1, 'frutos': 1},
 'h': {'habla': 1,
       'hacia': 1,
       'haya': 1,
       'hayas': 1,
       'hermana': 1,
       'hombre': 1,
       'hubiste': 1,
       'huye': 1},
 'i': {'intacto': 1},
 'j': {'jardines': 1},
 'l': {'la': 3,
       'labios': 1,
       'las': 7,
       'lo': 2,
       'los': 4,
       'luna': 1,
       'lévate': 1,
       'límpiate': 1},
 'm': {'mano': 1,
       'manos': 1,
       'margarita': 1,
       'me': 10,
       'mi': 1,
       'mieles': 1,
       'milagros': 1,
       'mojada;': 1,
       'montaña;': 1,
       'morados': 1},
 'n': {'negros': 1, 'ni': 2, 'no': 1, 'nácar': 1, 'nívea': 2},
 'p': {'perdone)': 2,
       'perfume': 1,
       'por': 2,
       'pretendes': 3,
       'preténdeme': 3,
       'puesto': 1,
       'pájaros': 1,
       'pámpanos': 1},
 'q': {'que': 6, 'quedó': 1, 'quieres': 6},
 'r': {'rayo': 1, 'raíz': 1, 'renueva': 1, 'rocas;': 1, 'rojo': 1},
 's': {'salitre': 1, 'se': 2, 'sea': 1, 'sean': 1, 'sobre': 2, 'sé': 1},
 't': {'te': 3,
       'tejidos': 1,
       'tenue': 1,
       'tierra': 1,
       'toca': 1,
       'todas': 2,
       'todavía': 1,
       'tornadas': 1,
       'tú': 8},
 'u': {'un': 1, 'una': 1},
 'v': {'vestido': 1, 'vete': 1, 'vive': 1},
 'y': {'y': 5}}

Para este ejercicio, se ha estructura el programa en tres funciones, cada una con un objetivo concreto. Siguiendo una lógica de concatenar un resultado al otro, para obtener un diccionario final ordenado por índices y alfabéticamente, de acuerdo a lo solicitado.

---------------------------------------------------------------------------------------------------------------------

2.Conversió de tipus de dades.

El client rep una llista de dades i necessita generar dues llistes, la primera on estaran tots els elements que es van poder convertir en flotants i l'altra on estan els elements que no es van poder convertir. Exemple de la llista que rep el client:

In [ ]:
conversion=["1.3", "one", "1e10", "seven","3-1/2", ('2',1,1.4,'not-a-number'),[1,2,'3','3.4']]

#Creamos una función para convertir en float los elementos de una lista
def convert_data_type(lista):
    lista_float = []
    lista_s_float = []
    for data in lista:
        #Utilizamos el método try/except para manejar el error de valores al intentar adicionar los datos a la lista
        try:
            lista_float.append(float(data))
        except ValueError:
            lista_s_float.append(data)
        except TypeError:
            #En el caso de error de tipo de dato, llamamos a la función para alojar en dos sublistas, aquellos elementos sin convertir  
            sub_float, sub_s_float = convert_data_type(data)
            lista_float.extend(sub_float)
            lista_s_float.extend(sub_s_float)
    return lista_float, lista_s_float

# Ejecutar la función y mostrar los resultados
floats, not_floats = convert_data_type(conversion)
print("Elementos convertidos a float:", floats)
print("Elementos NO convertibles a float:", not_floats)

Elementos convertidos a float: [1.3, 10000000000.0, 2.0, 1.0, 1.4, 1.0, 2.0, 3.0, 3.4]
Elementos NO convertibles a float: ['one', 'seven', '3-1/2', 'not-a-number']

En este ejercicio se crea la función para convertir el tipo de dato contenido en una lista a "float". Para ello se crean dos listas vacias para alojar los números convertidos y los que no son viables de conversión. Y mediante la excepción try/except, se manejan los posibles errores de valor y tipo de dato. Se crean ademas, dos sublistas, para alojar elementos que no fueron considerados en el primer bucle, y llamamos a la función para que nuevamente se ejecute. Con el método "extend" combinamos los elementos de la primera iteración con la segunda, en cada una de las listas, según corresponda.

---------------------------------------------------------------------------------------------------------------------

Nivel 3

1. Generador de Contrasenyes

En aquest punt, el client ha detectat un problema amb les contrasenyes que utilitzen els seus treballadors. Asdf1234, dates d’aniversari o similars. Per a solucionar-ho ens ha encarregat una funció de Python que generi contrasenyes més segures. La funció ha de dependre dels següents paràmetres:

-longitud (int): Longitud de la contrasenya
-majuscules (bool = True): Si hi ha d’aparèixer majúscules
-minuscules (bool = True): Si hi ha d’aparèixer minúscules
-numeros (bool = True): Si hi ha d’aparèixer números
-signes (bool = False): Si hi ha d’aparèixer caràcters especials (,-$? o similars)
Així doncs, si executem la funció de la següent manera:

crear_contrasenya(10, True, True, True, True)

Hauríem d’obtenir un output (que hem de poder guardar) de l’estil:

9Er,5Vn8P$

Assegura’t que es compleixin tots els criteris, i que aquestes contrasenyes siguin realment aleatòries.

(EXTRA) Explora com podríem fer que la funció copiés la contrasenya automàticament al porta papers de l’ordinador (com si l’haguéssim seleccionat i fet ctrl+copy).

2. Processament de dades simple

Una companya de feina ens ha demanat un favor, aprofitant que sap que estem aprenent a programar. Té un històric de partits de futbol català en un fitxer, on hi ha emmagatzemat els noms dels equips i els resultats. Necessita que processem les dades de manera automàtica, per extreure’n els resultats que necessita.

Utilitza el fitxer "historic_partits.txt"

Necessita un programa que retorni:

El nombre total de gols que ha fet cada equip.
El nom de l’equip més golejador.
El nom de l’equip més golejat
La classificació global (cada victòria: 3 pts, empat 1 pts, derrota 0 pts)

In [16]:
import pandas as pd
df_partidos = pd.read_csv(r"C:\Users\jprom\Desktop\IT Academy\Python\Data Analytics\Sprint 9\historic partits.txt")

# Dividir la columna única, en tres, usando tab como separador
df_partidos_split = df_partidos[df_partidos.columns[0]].str.split('\t', expand=True)
df_partidos_split.columns = ["Local", "Resultado", "Visitante"]


df_partidos_split

                   Local Resultado   Visitante
0             Vilafranca       4-5    Terrassa
1                   Olot       5-0  Granollers
2             Vilafranca       5-5     Manlleu
3               Cornellà       5-1        Prat
4             Cerdanyola       0-5  Vilafranca
..                   ...       ...         ...
494  Nàstic de Tarragona       1-3        Olot
495             Badalona       5-4        Prat
496                 Olot       4-5  Llagostera
497         FC Barcelona       3-1    Cornellà
498                 Olot       0-5  Granollers

[499 rows x 3 columns]

In [17]:
#Creamos una función que toma como argumento un df con los datos de los equipos (local, resultado y visitante), para calcular el total de goles por equipo

def total_goles(df):
    dic_total_goles_realizados = {}  # Inicializar el diccionario aquí
    for index, row in df.iterrows():
        local = row['Local']
        visitante = row['Visitante']
        resultado = row['Resultado']
        try:
            goles_local, goles_visitante = map(int, resultado.split('-'))
        except Exception:
            continue  # saltar si el resultado del formato es erróneo
        
        dic_total_goles_realizados[local] = dic_total_goles_realizados.get(local, 0) + goles_local
        dic_total_goles_realizados[visitante] = dic_total_goles_realizados.get(visitante, 0) + goles_visitante
        
      
    # Devolver el diccionario ordenado por cantidad de goles por equipo 
    return dict(sorted(dic_total_goles_realizados.items(), key=lambda item: item[1], reverse=True))
goles_por_equipo = total_goles(df_partidos_split)
goles_por_equipo

{'Figueres': 161,
 'Llagostera': 159,
 'Vilafranca': 157,
 'Terrassa': 147,
 'Cornellà': 147,
 'Sabadell': 141,
 'Girona FC': 139,
 'Badalona': 134,
 'Olot': 132,
 'RCD Espanyol': 131,
 'Nàstic de Tarragona': 130,
 'Lleida Esportiu': 129,
 'FC Barcelona': 125,
 'Sant Andreu': 123,
 'Granollers': 121,
 'Reus Deportiu': 119,
 'Cerdanyola': 117,
 'Manlleu': 106,
 'Prat': 106,
 'Europa': 93}

In [26]:
equipo_mas_goleador = list(goles_por_equipo.keys())[0]
print(f"El nombre del equipo mas goleador es:", equipo_mas_goleador)

El nombre del equipo mas goleador es: Figueres

In [12]:
def total_goles(df):
    dict_total_goles_recibidos = {}  # Inicializar el diccionario aquí
    for index, row in df.iterrows():
        local = row['Local']
        visitante = row['Visitante']
        resultado = row['Resultado']
        try:
            goles_local, goles_visitante = map(int, resultado.split('-'))
        except Exception:
            continue  # saltar si el resultado del formato es erróneo
        
        dict_total_goles_recibidos[local] = dict_total_goles_recibidos.get(local, 0) + goles_visitante
        dict_total_goles_recibidos[visitante] = dict_total_goles_recibidos.get(visitante, 0) + goles_local
      
    # Devolver el diccionario ordenado por cantidad de goles por equipo 
    return dict(sorted(dict_total_goles_recibidos.items(), key=lambda item: item[1], reverse=True))

goles_recibidos_por_equipo = total_goles(df_partidos_split)
goles_recibidos_por_equipo

{'Vilafranca': 172,
 'Terrassa': 164,
 'Figueres': 154,
 'Nàstic de Tarragona': 148,
 'Cornellà': 146,
 'Olot': 144,
 'RCD Espanyol': 144,
 'Llagostera': 142,
 'Sant Andreu': 134,
 'Cerdanyola': 133,
 'Lleida Esportiu': 133,
 'Badalona': 124,
 'Sabadell': 121,
 'Granollers': 117,
 'Manlleu': 117,
 'FC Barcelona': 115,
 'Prat': 111,
 'Reus Deportiu': 111,
 'Girona FC': 94,
 'Europa': 93}

In [25]:
equipo_mas_goles_recibidos = list(goles_recibidos_por_equipo.keys())[0]
print(f"El nombre del equipo que mas goles ha recibido es:", equipo_mas_goles_recibidos)

El nombre del equipo que mas goles ha recibido es: Vilafranca

In [30]:
def clasificacion(df):
    puntos = {}
    for index, row in df.iterrows():
        local = row['Local']
        visitante = row['Visitante']
        resultado = row['Resultado']
        try:
            goles_local, goles_visitante = map(int, resultado.split('-'))
        except Exception:
            continue  # saltar si el resultado del formato es erróneo

        # Inicializar equipos si no existen
        if local not in puntos:
            puntos[local] = 0
        if visitante not in puntos:
            puntos[visitante] = 0

        if goles_local > goles_visitante:
            puntos[local] += 3
        elif goles_local == goles_visitante:
            puntos[local] += 1
            puntos[visitante] += 1
        else:
            puntos[visitante] += 3
    # Ordenar por puntos descendente
    return dict(sorted(puntos.items(), key=lambda item: item[1], reverse=True))

clasificacion_global = clasificacion(df_partidos_split)
clasificacion_global

{'Girona FC': 96,
 'Llagostera': 94,
 'Sabadell': 85,
 'Cornellà': 82,
 'RCD Espanyol': 80,
 'Figueres': 79,
 'Lleida Esportiu': 75,
 'Terrassa': 74,
 'FC Barcelona': 73,
 'Vilafranca': 72,
 'Badalona': 68,
 'Reus Deportiu': 68,
 'Nàstic de Tarragona': 68,
 'Olot': 64,
 'Granollers': 64,
 'Sant Andreu': 62,
 'Manlleu': 57,
 'Prat': 56,
 'Cerdanyola': 56,
 'Europa': 41}

Para este ejercicio se ha optado por crear un DataFrame de 3 columnas (Local, Resultado, Visitante), mediante el uso de la libreria "pandas" y el método "split", para dividir la única columna, por tabulaciónes del texto proporcionado. 
Luego se define la primer función, para contabilizar la cantidad total de goles realizados, por cada uno de los equipos. Se crea un diccionario vacio, donde se alojarán los resultados del par clave, valor ("equipo", "goles"). Se itera mediante un bucle for, por cada fila del df, utilizando "index, row". Por cada fila iterada, mediante el método "iterrows", se devuelve una tupla, correspondiente al índice y un objeto con los datos de la fila.

Con el manejo de excepciones try/except, y mediante la función map, aplicamos a cada iterable de la tupla, el método "split", para separar en dos variables ("goles_local", "goles_visitante") los elementos contenidos en la variable creada previamente como "resultado".
Una vez separados estos valores, asignamos al diccionario creado inicialmente para contabilizar los goles realizados por cada equipo, considerando su posición ("local", "visitante" ) y obtener discrimando la cantidad total.
La segunda función es similar a la primera, solo que para contabilizar los goles recibidos, se invierte la operación, adicionando al equipo local, los goles del visitante, para obtener la cantidad efectiva de goles no efectuados.

Por último, la tercer función clasifica los equipos, a partir del DataFrame, de acuerdo al puntaje indicado para : victoria, empate, derrota. Para ello se crea un diccionario vacio, donde se alojaran, los datos de clave: valor, correspondiente al nombre del equipo y al total de puntos logrado. Mediante el método condicional (if/elif/else) se determinan los posibles escenarios para asignar el puntaje correspondiente a cada equipo.