### Nivell 1

Des d’un Jupyter Notebook faràs els següents exercicis utilitzant la llibreria requests de Python.

Exploració bàsica amb una API de laboratori.

1. Consulta l’API pública JSONPlaceholder utilitzant el mètode GET per obtenir:

Llista de publicacions (/posts)
Llista d’usuaris (/users)
Llista de tasques (/todos)

In [2]:
#Método de petición HTTP
%pip install requests
import requests
response = requests.get('https://jsonplaceholder.typicode.com/')

Requirement already satisfied: requests in c:\users\jprom\miniconda3\envs\myenv\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\jprom\miniconda3\envs\myenv\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jprom\miniconda3\envs\myenv\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jprom\miniconda3\envs\myenv\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jprom\miniconda3\envs\myenv\lib\site-packages (from requests) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [3]:
#Obtener la lista de posts
import requests
import json

# 1. Definir la URL de la API o web. 
url = "https://jsonplaceholder.typicode.com/posts" 

try:
    # 2. Realizar la petición GET
    response = requests.get(url)
    
    # 3. Verificar si la petición fue exitosa (código de estado 200)
    response.raise_for_status() 

    # 4. Parsear la respuesta en formato JSON a una lista de diccionarios de Python
    posts = response.json() 
    
    # 5. Iterar sobre la lista e imprime la información deseada de cada post
    print("Lista de posts obtenidos:")
    for post in posts:
      print(f"  ID: {post['id']}, Título: {post['title']}")
        
    # Imprimir la lista completa
    #print(json.dumps(posts, indent=2))

except requests.exceptions.RequestException as e:
    print(f"Error al realizar la petición: {e}")
except Exception as e:
    print(f"Ocurrió un error: {e}")

Lista de posts obtenidos:
  ID: 1, Título: sunt aut facere repellat provident occaecati excepturi optio reprehenderit
  ID: 2, Título: qui est esse
  ID: 3, Título: ea molestias quasi exercitationem repellat qui ipsa sit aut
  ID: 4, Título: eum et est occaecati
  ID: 5, Título: nesciunt quas odio
  ID: 6, Título: dolorem eum magni eos aperiam quia
  ID: 7, Título: magnam facilis autem
  ID: 8, Título: dolorem dolore est ipsam
  ID: 9, Título: nesciunt iure omnis dolorem tempora et accusantium
  ID: 10, Título: optio molestias id quia eum
  ID: 11, Título: et ea vero quia laudantium autem
  ID: 12, Título: in quibusdam tempore odit est dolorem
  ID: 13, Título: dolorum ut in voluptas mollitia et saepe quo animi
  ID: 14, Título: voluptatem eligendi optio
  ID: 15, Título: eveniet quod temporibus
  ID: 16, Título: sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio
  ID: 17, Título: fugit voluptas sed molestias voluptatem provident
  ID: 18, Título: voluptate et itaque vero tempora molestiae
  ID: 19, Título: adipisci placeat illum aut reiciendis qui
  ID: 20, Título: doloribus ad provident suscipit at
  ID: 21, Título: asperiores ea ipsam voluptatibus modi minima quia sint
  ID: 22, Título: dolor sint quo a velit explicabo quia nam
  ID: 23, Título: maxime id vitae nihil numquam
  ID: 24, Título: autem hic labore sunt dolores incidunt
  ID: 25, Título: rem alias distinctio quo quis
  ID: 26, Título: est et quae odit qui non
  ID: 27, Título: quasi id et eos tenetur aut quo autem
  ID: 28, Título: delectus ullam et corporis nulla voluptas sequi
  ID: 29, Título: iusto eius quod necessitatibus culpa ea
  ID: 30, Título: a quo magni similique perferendis
  ID: 31, Título: ullam ut quidem id aut vel consequuntur
  ID: 32, Título: doloremque illum aliquid sunt
  ID: 33, Título: qui explicabo molestiae dolorem
  ID: 34, Título: magnam ut rerum iure
  ID: 35, Título: id nihil consequatur molestias animi provident
  ID: 36, Título: fuga nam accusamus voluptas reiciendis itaque
  ID: 37, Título: provident vel ut sit ratione est
  ID: 38, Título: explicabo et eos deleniti nostrum ab id repellendus
  ID: 39, Título: eos dolorem iste accusantium est eaque quam
  ID: 40, Título: enim quo cumque
  ID: 41, Título: non est facere
  ID: 42, Título: commodi ullam sint et excepturi error explicabo praesentium voluptas
  ID: 43, Título: eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis
  ID: 44, Título: optio dolor molestias sit
  ID: 45, Título: ut numquam possimus omnis eius suscipit laudantium iure
  ID: 46, Título: aut quo modi neque nostrum ducimus
  ID: 47, Título: quibusdam cumque rem aut deserunt
  ID: 48, Título: ut voluptatem illum ea doloribus itaque eos
  ID: 49, Título: laborum non sunt aut ut assumenda perspiciatis voluptas
  ID: 50, Título: repellendus qui recusandae incidunt voluptates tenetur qui omnis exercitationem
  ID: 51, Título: soluta aliquam aperiam consequatur illo quis voluptas
  ID: 52, Título: qui enim et consequuntur quia animi quis voluptate quibusdam
  ID: 53, Título: ut quo aut ducimus alias
  ID: 54, Título: sit asperiores ipsam eveniet odio non quia
  ID: 55, Título: sit vel voluptatem et non libero
  ID: 56, Título: qui et at rerum necessitatibus
  ID: 57, Título: sed ab est est
  ID: 58, Título: voluptatum itaque dolores nisi et quasi
  ID: 59, Título: qui commodi dolor at maiores et quis id accusantium
  ID: 60, Título: consequatur placeat omnis quisquam quia reprehenderit fugit veritatis facere
  ID: 61, Título: voluptatem doloribus consectetur est ut ducimus
  ID: 62, Título: beatae enim quia vel
  ID: 63, Título: voluptas blanditiis repellendus animi ducimus error sapiente et suscipit
  ID: 64, Título: et fugit quas eum in in aperiam quod
  ID: 65, Título: consequatur id enim sunt et et
  ID: 66, Título: repudiandae ea animi iusto
  ID: 67, Título: aliquid eos sed fuga est maxime repellendus
  ID: 68, Título: odio quis facere architecto reiciendis optio
  ID: 69, Título: fugiat quod pariatur odit minima
  ID: 70, Título: voluptatem laborum magni
  ID: 71, Título: et iusto veniam et illum aut fuga
  ID: 72, Título: sint hic doloribus consequatur eos non id
  ID: 73, Título: consequuntur deleniti eos quia temporibus ab aliquid at
  ID: 74, Título: enim unde ratione doloribus quas enim ut sit sapiente
  ID: 75, Título: dignissimos eum dolor ut enim et delectus in
  ID: 76, Título: doloremque officiis ad et non perferendis
  ID: 77, Título: necessitatibus quasi exercitationem odio
  ID: 78, Título: quam voluptatibus rerum veritatis
  ID: 79, Título: pariatur consequatur quia magnam autem omnis non amet
  ID: 80, Título: labore in ex et explicabo corporis aut quas
  ID: 81, Título: tempora rem veritatis voluptas quo dolores vero
  ID: 82, Título: laudantium voluptate suscipit sunt enim enim
  ID: 83, Título: odit et voluptates doloribus alias odio et
  ID: 84, Título: optio ipsam molestias necessitatibus occaecati facilis veritatis dolores aut
  ID: 85, Título: dolore veritatis porro provident adipisci blanditiis et sunt
  ID: 86, Título: placeat quia et porro iste
  ID: 87, Título: nostrum quis quasi placeat
  ID: 88, Título: sapiente omnis fugit eos
  ID: 89, Título: sint soluta et vel magnam aut ut sed qui
  ID: 90, Título: ad iusto omnis odit dolor voluptatibus
  ID: 91, Título: aut amet sed
  ID: 92, Título: ratione ex tenetur perferendis
  ID: 93, Título: beatae soluta recusandae
  ID: 94, Título: qui qui voluptates illo iste minima
  ID: 95, Título: id minus libero illum nam ad officiis
  ID: 96, Título: quaerat velit veniam amet cupiditate aut numquam ut sequi
  ID: 97, Título: quas fugiat ut perspiciatis vero provident
  ID: 98, Título: laboriosam dolor voluptates
  ID: 99, Título: temporibus sit alias delectus eligendi possimus magni
  ID: 100, Título: at nam consequatur ea labore ea harum

In [4]:
#Obtener la lista de users
import requests
import json

# 1. Definir la URL de la API o web. 
url = "https://jsonplaceholder.typicode.com/users" 

try:
    # 2. Realizar la petición GET
    response = requests.get(url)
    
    # 3. Verificar si la petición fue exitosa (código de estado 200)
    response.raise_for_status() 

    # 4. Parsear la respuesta en formato JSON a una lista de diccionarios de Python
    users = response.json() 
    
    # 5. Iterar sobre la lista e imprime la información deseada de cada post
    print("Lista de users obtenidos:")
  
    # Imprimir la lista completa
    print(json.dumps(users, indent=2))

except requests.exceptions.RequestException as e:
    print(f"Error al realizar la petición: {e}")
except Exception as e:
    print(f"Ocurrió un error: {e}")

Lista de users obtenidos:
[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net",
    "company": {
      "name": "Deckow-Crist",
      "catchPhrase": "Proactive didactic contingency",
      "bs": "synergize scalable supply-chains"
    }
  },
  {
    "id": 3,
    "name": "Clementine Bauch",
    "username": "Samantha",
    "email": "Nathan@yesenia.net",
    "address": {
      "street": "Douglas Extension",
      "suite": "Suite 847",
      "city": "McKenziehaven",
      "zipcode": "59590-4157",
      "geo": {
        "lat": "-68.6102",
        "lng": "-47.0653"
      }
    },
    "phone": "1-463-123-4447",
    "website": "ramiro.info",
    "company": {
      "name": "Romaguera-Jacobson",
      "catchPhrase": "Face to face bifurcated interface",
      "bs": "e-enable strategic applications"
    }
  },
  {
    "id": 4,
    "name": "Patricia Lebsack",
    "username": "Karianne",
    "email": "Julianne.OConner@kory.org",
    "address": {
      "street": "Hoeger Mall",
      "suite": "Apt. 692",
      "city": "South Elvis",
      "zipcode": "53919-4257",
      "geo": {
        "lat": "29.4572",
        "lng": "-164.2990"
      }
    },
    "phone": "493-170-9623 x156",
    "website": "kale.biz",
    "company": {
      "name": "Robel-Corkery",
      "catchPhrase": "Multi-tiered zero tolerance productivity",
      "bs": "transition cutting-edge web services"
    }
  },
  {
    "id": 5,
    "name": "Chelsey Dietrich",
    "username": "Kamren",
    "email": "Lucio_Hettinger@annie.ca",
    "address": {
      "street": "Skiles Walks",
      "suite": "Suite 351",
      "city": "Roscoeview",
      "zipcode": "33263",
      "geo": {
        "lat": "-31.8129",
        "lng": "62.5342"
      }
    },
    "phone": "(254)954-1289",
    "website": "demarco.info",
    "company": {
      "name": "Keebler LLC",
      "catchPhrase": "User-centric fault-tolerant solution",
      "bs": "revolutionize end-to-end systems"
    }
  },
  {
    "id": 6,
    "name": "Mrs. Dennis Schulist",
    "username": "Leopoldo_Corkery",
    "email": "Karley_Dach@jasper.info",
    "address": {
      "street": "Norberto Crossing",
      "suite": "Apt. 950",
      "city": "South Christy",
      "zipcode": "23505-1337",
      "geo": {
        "lat": "-71.4197",
        "lng": "71.7478"
      }
    },
    "phone": "1-477-935-8478 x6430",
    "website": "ola.org",
    "company": {
      "name": "Considine-Lockman",
      "catchPhrase": "Synchronised bottom-line interface",
      "bs": "e-enable innovative applications"
    }
  },
  {
    "id": 7,
    "name": "Kurtis Weissnat",
    "username": "Elwyn.Skiles",
    "email": "Telly.Hoeger@billy.biz",
    "address": {
      "street": "Rex Trail",
      "suite": "Suite 280",
      "city": "Howemouth",
      "zipcode": "58804-1099",
      "geo": {
        "lat": "24.8918",
        "lng": "21.8984"
      }
    },
    "phone": "210.067.6132",
    "website": "elvis.io",
    "company": {
      "name": "Johns Group",
      "catchPhrase": "Configurable multimedia task-force",
      "bs": "generate enterprise e-tailers"
    }
  },
  {
    "id": 8,
    "name": "Nicholas Runolfsdottir V",
    "username": "Maxime_Nienow",
    "email": "Sherwood@rosamond.me",
    "address": {
      "street": "Ellsworth Summit",
      "suite": "Suite 729",
      "city": "Aliyaview",
      "zipcode": "45169",
      "geo": {
        "lat": "-14.3990",
        "lng": "-120.7677"
      }
    },
    "phone": "586.493.6943 x140",
    "website": "jacynthe.com",
    "company": {
      "name": "Abernathy Group",
      "catchPhrase": "Implemented secondary concept",
      "bs": "e-enable extensible e-tailers"
    }
  },
  {
    "id": 9,
    "name": "Glenna Reichert",
    "username": "Delphine",
    "email": "Chaim_McDermott@dana.io",
    "address": {
      "street": "Dayna Park",
      "suite": "Suite 449",
      "city": "Bartholomebury",
      "zipcode": "76495-3109",
      "geo": {
        "lat": "24.6463",
        "lng": "-168.8889"
      }
    },
    "phone": "(775)976-6794 x41206",
    "website": "conrad.com",
    "company": {
      "name": "Yost and Sons",
      "catchPhrase": "Switchable contextually-based project",
      "bs": "aggregate real-time technologies"
    }
  },
  {
    "id": 10,
    "name": "Clementina DuBuque",
    "username": "Moriah.Stanton",
    "email": "Rey.Padberg@karina.biz",
    "address": {
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "zipcode": "31428-2261",
      "geo": {
        "lat": "-38.2386",
        "lng": "57.2232"
      }
    },
    "phone": "024-648-3804",
    "website": "ambrose.net",
    "company": {
      "name": "Hoeger LLC",
      "catchPhrase": "Centralized empowering task-force",
      "bs": "target end-to-end models"
    }
  }
]

In [5]:
#Obtener la lista de posts
import requests
import json

# 1. Definir la URL de la API o web. 
url = "https://jsonplaceholder.typicode.com/todos" 

try:
    # 2. Realizar la petición GET
    response = requests.get(url)
    
    # 3. Verificar si la petición fue exitosa (código de estado 200)
    response.raise_for_status() 

    # 4. Parsear la respuesta en formato JSON a una lista de diccionarios de Python
    tasks = response.json() 
    
    # 5. Iterar sobre la lista e imprime la información deseada de cada post
    print("Lista de tareas obtenidas:")
    # Imprimir la lista completa
    print(json.dumps(tasks, indent=2))

except requests.exceptions.RequestException as e:
    print(f"Error al realizar la petición: {e}")
except Exception as e:
    print(f"Ocurrió un error: {e}")

Lista de tareas obtenidas:
[
  {
    "userId": 1,
    "id": 1,
    "title": "delectus aut autem",
    "completed": false
  },
  {
    "userId": 1,
    "id": 2,
    "title": "quis ut nam facilis et officia qui",
    "completed": false
  },
  {
    "userId": 1,
    "id": 3,
    "title": "fugiat veniam minus",
    "completed": false
  },
  {
    "userId": 1,
    "id": 4,
    "title": "et porro tempora",
    "completed": true
  },
  {
    "userId": 1,
    "id": 5,
    "title": "laboriosam mollitia et enim quasi adipisci quia provident illum",
    "completed": false
  },
  {
    "userId": 1,
    "id": 6,
    "title": "qui ullam ratione quibusdam voluptatem quia omnis",
    "completed": false
  },
  {
    "userId": 1,
    "id": 7,
    "title": "illo expedita consequatur quia in",
    "completed": false
  },
  {
    "userId": 1,
    "id": 8,
    "title": "quo adipisci enim quam ut ab",
    "completed": true
  },
  {
    "userId": 1,
    "id": 9,
    "title": "molestiae perspiciatis ipsa",
    "completed": false
  },
  {
    "userId": 1,
    "id": 10,
    "title": "illo est ratione doloremque quia maiores aut",
    "completed": true
  },
  {
    "userId": 1,
    "id": 11,
    "title": "vero rerum temporibus dolor",
    "completed": true
  },
  {
    "userId": 1,
    "id": 12,
    "title": "ipsa repellendus fugit nisi",
    "completed": true
  },
  {
    "userId": 1,
    "id": 13,
    "title": "et doloremque nulla",
    "completed": false
  },
  {
    "userId": 1,
    "id": 14,
    "title": "repellendus sunt dolores architecto voluptatum",
    "completed": true
  },
  {
    "userId": 1,
    "id": 15,
    "title": "ab voluptatum amet voluptas",
    "completed": true
  },
  {
    "userId": 1,
    "id": 16,
    "title": "accusamus eos facilis sint et aut voluptatem",
    "completed": true
  },
  {
    "userId": 1,
    "id": 17,
    "title": "quo laboriosam deleniti aut qui",
    "completed": true
  },
  {
    "userId": 1,
    "id": 18,
    "title": "dolorum est consequatur ea mollitia in culpa",
    "completed": false
  },
  {
    "userId": 1,
    "id": 19,
    "title": "molestiae ipsa aut voluptatibus pariatur dolor nihil",
    "completed": true
  },
  {
    "userId": 1,
    "id": 20,
    "title": "ullam nobis libero sapiente ad optio sint",
    "completed": true
  },
  {
    "userId": 2,
    "id": 21,
    "title": "suscipit repellat esse quibusdam voluptatem incidunt",
    "completed": false
  },
  {
    "userId": 2,
    "id": 22,
    "title": "distinctio vitae autem nihil ut molestias quo",
    "completed": true
  },
  {
    "userId": 2,
    "id": 23,
    "title": "et itaque necessitatibus maxime molestiae qui quas velit",
    "completed": false
  },
  {
    "userId": 2,
    "id": 24,
    "title": "adipisci non ad dicta qui amet quaerat doloribus ea",
    "completed": false
  },
  {
    "userId": 2,
    "id": 25,
    "title": "voluptas quo tenetur perspiciatis explicabo natus",
    "completed": true
  },
  {
    "userId": 2,
    "id": 26,
    "title": "aliquam aut quasi",
    "completed": true
  },
  {
    "userId": 2,
    "id": 27,
    "title": "veritatis pariatur delectus",
    "completed": true
  },
  {
    "userId": 2,
    "id": 28,
    "title": "nesciunt totam sit blanditiis sit",
    "completed": false
  },
  {
    "userId": 2,
    "id": 29,
    "title": "laborum aut in quam",
    "completed": false
  },
  {
    "userId": 2,
    "id": 30,
    "title": "nemo perspiciatis repellat ut dolor libero commodi blanditiis omnis",
    "completed": true
  },
  {
    "userId": 2,
    "id": 31,
    "title": "repudiandae totam in est sint facere fuga",
    "completed": false
  },
  {
    "userId": 2,
    "id": 32,
    "title": "earum doloribus ea doloremque quis",
    "completed": false
  },
  {
    "userId": 2,
    "id": 33,
    "title": "sint sit aut vero",
    "completed": false
  },
  {
    "userId": 2,
    "id": 34,
    "title": "porro aut necessitatibus eaque distinctio",
    "completed": false
  },
  {
    "userId": 2,
    "id": 35,
    "title": "repellendus veritatis molestias dicta incidunt",
    "completed": true
  },
  {
    "userId": 2,
    "id": 36,
    "title": "excepturi deleniti adipisci voluptatem et neque optio illum ad",
    "completed": true
  },
  {
    "userId": 2,
    "id": 37,
    "title": "sunt cum tempora",
    "completed": false
  },
  {
    "userId": 2,
    "id": 38,
    "title": "totam quia non",
    "completed": false
  },
  {
    "userId": 2,
    "id": 39,
    "title": "doloremque quibusdam asperiores libero corrupti illum qui omnis",
    "completed": false
  },
  {
    "userId": 2,
    "id": 40,
    "title": "totam atque quo nesciunt",
    "completed": true
  },
  {
    "userId": 3,
    "id": 41,
    "title": "aliquid amet impedit consequatur aspernatur placeat eaque fugiat suscipit",
    "completed": false
  },
  {
    "userId": 3,
    "id": 42,
    "title": "rerum perferendis error quia ut eveniet",
    "completed": false
  },
  {
    "userId": 3,
    "id": 43,
    "title": "tempore ut sint quis recusandae",
    "completed": true
  },
  {
    "userId": 3,
    "id": 44,
    "title": "cum debitis quis accusamus doloremque ipsa natus sapiente omnis",
    "completed": true
  },
  {
    "userId": 3,
    "id": 45,
    "title": "velit soluta adipisci molestias reiciendis harum",
    "completed": false
  },
  {
    "userId": 3,
    "id": 46,
    "title": "vel voluptatem repellat nihil placeat corporis",
    "completed": false
  },
  {
    "userId": 3,
    "id": 47,
    "title": "nam qui rerum fugiat accusamus",
    "completed": false
  },
  {
    "userId": 3,
    "id": 48,
    "title": "sit reprehenderit omnis quia",
    "completed": false
  },
  {
    "userId": 3,
    "id": 49,
    "title": "ut necessitatibus aut maiores debitis officia blanditiis velit et",
    "completed": false
  },
  {
    "userId": 3,
    "id": 50,
    "title": "cupiditate necessitatibus ullam aut quis dolor voluptate",
    "completed": true
  },
  {
    "userId": 3,
    "id": 51,
    "title": "distinctio exercitationem ab doloribus",
    "completed": false
  },
  {
    "userId": 3,
    "id": 52,
    "title": "nesciunt dolorum quis recusandae ad pariatur ratione",
    "completed": false
  },
  {
    "userId": 3,
    "id": 53,
    "title": "qui labore est occaecati recusandae aliquid quam",
    "completed": false
  },
  {
    "userId": 3,
    "id": 54,
    "title": "quis et est ut voluptate quam dolor",
    "completed": true
  },
  {
    "userId": 3,
    "id": 55,
    "title": "voluptatum omnis minima qui occaecati provident nulla voluptatem ratione",
    "completed": true
  },
  {
    "userId": 3,
    "id": 56,
    "title": "deleniti ea temporibus enim",
    "completed": true
  },
  {
    "userId": 3,
    "id": 57,
    "title": "pariatur et magnam ea doloribus similique voluptatem rerum quia",
    "completed": false
  },
  {
    "userId": 3,
    "id": 58,
    "title": "est dicta totam qui explicabo doloribus qui dignissimos",
    "completed": false
  },
  {
    "userId": 3,
    "id": 59,
    "title": "perspiciatis velit id laborum placeat iusto et aliquam odio",
    "completed": false
  },
  {
    "userId": 3,
    "id": 60,
    "title": "et sequi qui architecto ut adipisci",
    "completed": true
  },
  {
    "userId": 4,
    "id": 61,
    "title": "odit optio omnis qui sunt",
    "completed": true
  },
  {
    "userId": 4,
    "id": 62,
    "title": "et placeat et tempore aspernatur sint numquam",
    "completed": false
  },
  {
    "userId": 4,
    "id": 63,
    "title": "doloremque aut dolores quidem fuga qui nulla",
    "completed": true
  },
  {
    "userId": 4,
    "id": 64,
    "title": "voluptas consequatur qui ut quia magnam nemo esse",
    "completed": false
  },
  {
    "userId": 4,
    "id": 65,
    "title": "fugiat pariatur ratione ut asperiores necessitatibus magni",
    "completed": false
  },
  {
    "userId": 4,
    "id": 66,
    "title": "rerum eum molestias autem voluptatum sit optio",
    "completed": false
  },
  {
    "userId": 4,
    "id": 67,
    "title": "quia voluptatibus voluptatem quos similique maiores repellat",
    "completed": false
  },
  {
    "userId": 4,
    "id": 68,
    "title": "aut id perspiciatis voluptatem iusto",
    "completed": false
  },
  {
    "userId": 4,
    "id": 69,
    "title": "doloribus sint dolorum ab adipisci itaque dignissimos aliquam suscipit",
    "completed": false
  },
  {
    "userId": 4,
    "id": 70,
    "title": "ut sequi accusantium et mollitia delectus sunt",
    "completed": false
  },
  {
    "userId": 4,
    "id": 71,
    "title": "aut velit saepe ullam",
    "completed": false
  },
  {
    "userId": 4,
    "id": 72,
    "title": "praesentium facilis facere quis harum voluptatibus voluptatem eum",
    "completed": false
  },
  {
    "userId": 4,
    "id": 73,
    "title": "sint amet quia totam corporis qui exercitationem commodi",
    "completed": true
  },
  {
    "userId": 4,
    "id": 74,
    "title": "expedita tempore nobis eveniet laborum maiores",
    "completed": false
  },
  {
    "userId": 4,
    "id": 75,
    "title": "occaecati adipisci est possimus totam",
    "completed": false
  },
  {
    "userId": 4,
    "id": 76,
    "title": "sequi dolorem sed",
    "completed": true
  },
  {
    "userId": 4,
    "id": 77,
    "title": "maiores aut nesciunt delectus exercitationem vel assumenda eligendi at",
    "completed": false
  },
  {
    "userId": 4,
    "id": 78,
    "title": "reiciendis est magnam amet nemo iste recusandae impedit quaerat",
    "completed": false
  },
  {
    "userId": 4,
    "id": 79,
    "title": "eum ipsa maxime ut",
    "completed": true
  },
  {
    "userId": 4,
    "id": 80,
    "title": "tempore molestias dolores rerum sequi voluptates ipsum consequatur",
    "completed": true
  },
  {
    "userId": 5,
    "id": 81,
    "title": "suscipit qui totam",
    "completed": true
  },
  {
    "userId": 5,
    "id": 82,
    "title": "voluptates eum voluptas et dicta",
    "completed": false
  },
  {
    "userId": 5,
    "id": 83,
    "title": "quidem at rerum quis ex aut sit quam",
    "completed": true
  },
  {
    "userId": 5,
    "id": 84,
    "title": "sunt veritatis ut voluptate",
    "completed": false
  },
  {
    "userId": 5,
    "id": 85,
    "title": "et quia ad iste a",
    "completed": true
  },
  {
    "userId": 5,
    "id": 86,
    "title": "incidunt ut saepe autem",
    "completed": true
  },
  {
    "userId": 5,
    "id": 87,
    "title": "laudantium quae eligendi consequatur quia et vero autem",
    "completed": true
  },
  {
    "userId": 5,
    "id": 88,
    "title": "vitae aut excepturi laboriosam sint aliquam et et accusantium",
    "completed": false
  },
  {
    "userId": 5,
    "id": 89,
    "title": "sequi ut omnis et",
    "completed": true
  },
  {
    "userId": 5,
    "id": 90,
    "title": "molestiae nisi accusantium tenetur dolorem et",
    "completed": true
  },
  {
    "userId": 5,
    "id": 91,
    "title": "nulla quis consequatur saepe qui id expedita",
    "completed": true
  },
  {
    "userId": 5,
    "id": 92,
    "title": "in omnis laboriosam",
    "completed": true
  },
  {
    "userId": 5,
    "id": 93,
    "title": "odio iure consequatur molestiae quibusdam necessitatibus quia sint",
    "completed": true
  },
  {
    "userId": 5,
    "id": 94,
    "title": "facilis modi saepe mollitia",
    "completed": false
  },
  {
    "userId": 5,
    "id": 95,
    "title": "vel nihil et molestiae iusto assumenda nemo quo ut",
    "completed": true
  },
  {
    "userId": 5,
    "id": 96,
    "title": "nobis suscipit ducimus enim asperiores voluptas",
    "completed": false
  },
  {
    "userId": 5,
    "id": 97,
    "title": "dolorum laboriosam eos qui iure aliquam",
    "completed": false
  },
  {
    "userId": 5,
    "id": 98,
    "title": "debitis accusantium ut quo facilis nihil quis sapiente necessitatibus",
    "completed": true
  },
  {
    "userId": 5,
    "id": 99,
    "title": "neque voluptates ratione",
    "completed": false
  },
  {
    "userId": 5,
    "id": 100,
    "title": "excepturi a et neque qui expedita vel voluptate",
    "completed": false
  },
  {
    "userId": 6,
    "id": 101,
    "title": "explicabo enim cumque porro aperiam occaecati minima",
    "completed": false
  },
  {
    "userId": 6,
    "id": 102,
    "title": "sed ab consequatur",
    "completed": false
  },
  {
    "userId": 6,
    "id": 103,
    "title": "non sunt delectus illo nulla tenetur enim omnis",
    "completed": false
  },
  {
    "userId": 6,
    "id": 104,
    "title": "excepturi non laudantium quo",
    "completed": false
  },
  {
    "userId": 6,
    "id": 105,
    "title": "totam quia dolorem et illum repellat voluptas optio",
    "completed": true
  },
  {
    "userId": 6,
    "id": 106,
    "title": "ad illo quis voluptatem temporibus",
    "completed": true
  },
  {
    "userId": 6,
    "id": 107,
    "title": "praesentium facilis omnis laudantium fugit ad iusto nihil nesciunt",
    "completed": false
  },
  {
    "userId": 6,
    "id": 108,
    "title": "a eos eaque nihil et exercitationem incidunt delectus",
    "completed": true
  },
  {
    "userId": 6,
    "id": 109,
    "title": "autem temporibus harum quisquam in culpa",
    "completed": true
  },
  {
    "userId": 6,
    "id": 110,
    "title": "aut aut ea corporis",
    "completed": true
  },
  {
    "userId": 6,
    "id": 111,
    "title": "magni accusantium labore et id quis provident",
    "completed": false
  },
  {
    "userId": 6,
    "id": 112,
    "title": "consectetur impedit quisquam qui deserunt non rerum consequuntur eius",
    "completed": false
  },
  {
    "userId": 6,
    "id": 113,
    "title": "quia atque aliquam sunt impedit voluptatum rerum assumenda nisi",
    "completed": false
  },
  {
    "userId": 6,
    "id": 114,
    "title": "cupiditate quos possimus corporis quisquam exercitationem beatae",
    "completed": false
  },
  {
    "userId": 6,
    "id": 115,
    "title": "sed et ea eum",
    "completed": false
  },
  {
    "userId": 6,
    "id": 116,
    "title": "ipsa dolores vel facilis ut",
    "completed": true
  },
  {
    "userId": 6,
    "id": 117,
    "title": "sequi quae est et qui qui eveniet asperiores",
    "completed": false
  },
  {
    "userId": 6,
    "id": 118,
    "title": "quia modi consequatur vero fugiat",
    "completed": false
  },
  {
    "userId": 6,
    "id": 119,
    "title": "corporis ducimus ea perspiciatis iste",
    "completed": false
  },
  {
    "userId": 6,
    "id": 120,
    "title": "dolorem laboriosam vel voluptas et aliquam quasi",
    "completed": false
  },
  {
    "userId": 7,
    "id": 121,
    "title": "inventore aut nihil minima laudantium hic qui omnis",
    "completed": true
  },
  {
    "userId": 7,
    "id": 122,
    "title": "provident aut nobis culpa",
    "completed": true
  },
  {
    "userId": 7,
    "id": 123,
    "title": "esse et quis iste est earum aut impedit",
    "completed": false
  },
  {
    "userId": 7,
    "id": 124,
    "title": "qui consectetur id",
    "completed": false
  },
  {
    "userId": 7,
    "id": 125,
    "title": "aut quasi autem iste tempore illum possimus",
    "completed": false
  },
  {
    "userId": 7,
    "id": 126,
    "title": "ut asperiores perspiciatis veniam ipsum rerum saepe",
    "completed": true
  },
  {
    "userId": 7,
    "id": 127,
    "title": "voluptatem libero consectetur rerum ut",
    "completed": true
  },
  {
    "userId": 7,
    "id": 128,
    "title": "eius omnis est qui voluptatem autem",
    "completed": false
  },
  {
    "userId": 7,
    "id": 129,
    "title": "rerum culpa quis harum",
    "completed": false
  },
  {
    "userId": 7,
    "id": 130,
    "title": "nulla aliquid eveniet harum laborum libero alias ut unde",
    "completed": true
  },
  {
    "userId": 7,
    "id": 131,
    "title": "qui ea incidunt quis",
    "completed": false
  },
  {
    "userId": 7,
    "id": 132,
    "title": "qui molestiae voluptatibus velit iure harum quisquam",
    "completed": true
  },
  {
    "userId": 7,
    "id": 133,
    "title": "et labore eos enim rerum consequatur sunt",
    "completed": true
  },
  {
    "userId": 7,
    "id": 134,
    "title": "molestiae doloribus et laborum quod ea",
    "completed": false
  },
  {
    "userId": 7,
    "id": 135,
    "title": "facere ipsa nam eum voluptates reiciendis vero qui",
    "completed": false
  },
  {
    "userId": 7,
    "id": 136,
    "title": "asperiores illo tempora fuga sed ut quasi adipisci",
    "completed": false
  },
  {
    "userId": 7,
    "id": 137,
    "title": "qui sit non",
    "completed": false
  },
  {
    "userId": 7,
    "id": 138,
    "title": "placeat minima consequatur rem qui ut",
    "completed": true
  },
  {
    "userId": 7,
    "id": 139,
    "title": "consequatur doloribus id possimus voluptas a voluptatem",
    "completed": false
  },
  {
    "userId": 7,
    "id": 140,
    "title": "aut consectetur in blanditiis deserunt quia sed laboriosam",
    "completed": true
  },
  {
    "userId": 8,
    "id": 141,
    "title": "explicabo consectetur debitis voluptates quas quae culpa rerum non",
    "completed": true
  },
  {
    "userId": 8,
    "id": 142,
    "title": "maiores accusantium architecto necessitatibus reiciendis ea aut",
    "completed": true
  },
  {
    "userId": 8,
    "id": 143,
    "title": "eum non recusandae cupiditate animi",
    "completed": false
  },
  {
    "userId": 8,
    "id": 144,
    "title": "ut eum exercitationem sint",
    "completed": false
  },
  {
    "userId": 8,
    "id": 145,
    "title": "beatae qui ullam incidunt voluptatem non nisi aliquam",
    "completed": false
  },
  {
    "userId": 8,
    "id": 146,
    "title": "molestiae suscipit ratione nihil odio libero impedit vero totam",
    "completed": true
  },
  {
    "userId": 8,
    "id": 147,
    "title": "eum itaque quod reprehenderit et facilis dolor autem ut",
    "completed": true
  },
  {
    "userId": 8,
    "id": 148,
    "title": "esse quas et quo quasi exercitationem",
    "completed": false
  },
  {
    "userId": 8,
    "id": 149,
    "title": "animi voluptas quod perferendis est",
    "completed": false
  },
  {
    "userId": 8,
    "id": 150,
    "title": "eos amet tempore laudantium fugit a",
    "completed": false
  },
  {
    "userId": 8,
    "id": 151,
    "title": "accusamus adipisci dicta qui quo ea explicabo sed vero",
    "completed": true
  },
  {
    "userId": 8,
    "id": 152,
    "title": "odit eligendi recusandae doloremque cumque non",
    "completed": false
  },
  {
    "userId": 8,
    "id": 153,
    "title": "ea aperiam consequatur qui repellat eos",
    "completed": false
  },
  {
    "userId": 8,
    "id": 154,
    "title": "rerum non ex sapiente",
    "completed": true
  },
  {
    "userId": 8,
    "id": 155,
    "title": "voluptatem nobis consequatur et assumenda magnam",
    "completed": true
  },
  {
    "userId": 8,
    "id": 156,
    "title": "nam quia quia nulla repellat assumenda quibusdam sit nobis",
    "completed": true
  },
  {
    "userId": 8,
    "id": 157,
    "title": "dolorem veniam quisquam deserunt repellendus",
    "completed": true
  },
  {
    "userId": 8,
    "id": 158,
    "title": "debitis vitae delectus et harum accusamus aut deleniti a",
    "completed": true
  },
  {
    "userId": 8,
    "id": 159,
    "title": "debitis adipisci quibusdam aliquam sed dolore ea praesentium nobis",
    "completed": true
  },
  {
    "userId": 8,
    "id": 160,
    "title": "et praesentium aliquam est",
    "completed": false
  },
  {
    "userId": 9,
    "id": 161,
    "title": "ex hic consequuntur earum omnis alias ut occaecati culpa",
    "completed": true
  },
  {
    "userId": 9,
    "id": 162,
    "title": "omnis laboriosam molestias animi sunt dolore",
    "completed": true
  },
  {
    "userId": 9,
    "id": 163,
    "title": "natus corrupti maxime laudantium et voluptatem laboriosam odit",
    "completed": false
  },
  {
    "userId": 9,
    "id": 164,

2. Mostra per pantalla:

La quantitat total de cada recurs.
El codi d'estat de cada petició.

In [6]:
#Cantidad de posts
print(f"Cantidad total de posts: {len(posts)}")

# Get the status code by making a fresh request or storing the response earlier
response_posts = requests.get("https://jsonplaceholder.typicode.com/posts")
print(f"Código de estado: {response_posts.status_code}")

Cantidad total de posts: 100
Código de estado: 200

In [7]:
#Cantidad de users
print(f"Cantidad total de users: {len(users)}")

# Get the status code by making a fresh request or storing the response earlier
response_users = requests.get("https://jsonplaceholder.typicode.com/users")
print(f"Código de estado: {response_users.status_code}")

Cantidad total de users: 10
Código de estado: 200

In [8]:
#Cantidad de tasks
print(f"Cantidad total de tareas: {len(tasks)}")


# Get the status code by making a fresh request or storing the response earlier
response_tasks = requests.get("https://jsonplaceholder.typicode.com/todos")
print(f"Código de estado: {response_tasks.status_code}")

Cantidad total de tareas: 200
Código de estado: 200

3. Fes una petició a una publicació inexistent per obtenir un error 404 i mostra el codi d'estat rebut.

In [9]:
#Obtener una publicación inexistente y mostrar el código de estatus
url = "https://jsonplaceholder.typicode.com/posts/9999"

try:
    response = requests.get(url)
    
    print(f"Código de estado: {response.status_code}")
    
    if response.status_code == 200:
        print("GET request successful!")
        print("Response:")
        print(response.json())
    elif response.status_code == 404:
        print("Error 404: La publicación no existe")
        print("Response:")
        print(response.text)
    else:
        print(f"GET request failed with status code {response.status_code}")
        
except requests.exceptions.RequestException as e:
    print(f"Error al realizar la petición: {e}")

Código de estado: 404
Error 404: La publicación no existe
Response:
{}

4. Fes una petició POST per crear una nova publicació fictícia. Inclou el títol, el cos del missatge i un userId.

Mostra la resposta JSON.
Mostra el codi d'estat.

In [10]:
#Crear una nueva publicación mediante POST 
data_post = {'Título': 'Esto es una publicación de prueba', 'user_Id':'7'}
response = requests.post('https://jsonplaceholder.typicode.com/posts', data= data_post)
new_post = response.json()
print(f'Nueva publicación', new_post)
response.status_code

Nueva publicación {'Título': 'Esto es una publicación de prueba', 'user_Id': '7', 'id': 101}

201

5. Fes una petició PATCH per modificar parcialment una publicació existent.

Mostra la resposta JSON.
Mostra el codi d'estat

In [11]:
#Modificar una publicación parcialmente usando PATCH
new_data = {'Título':'Little Wing'}

# Realizar la petición PATCH
response = requests.patch('https://jsonplaceholder.typicode.com/posts/101', data=json.dumps(new_data))

# Verificar la respuesta del servidor
if response.status_code == 200:
    print("Post actualizado con éxito:")
    print(response.json())
else:
    print(f"Error al actualizar el post. Código de estado: {response.status_code}")
    print(response.text)

Post actualizado con éxito:
{}

6. Fes una petició DELETE sobre una publicació.

Mostra la resposta JSON.
Mostra el codi d'estat

In [ ]:
#Borrar una publicación mediante DELETE
response = requests.delete(url, data= {'id': '101'})
deleted_post = response.json()
response.status_code

200

---------------------------------------------------------------------------------------------------------------------

### Nivell 2
Interacció amb una API pública real

1. Explora el repositori de Public APIs i tria una API que permeti fer peticions GET.

In [19]:
#Irisnet API
import requests
response = requests.get('https://api.thedogapi.com')
response.json()

{'message': 'The Dog API', 'version': '1.4.5'}

2. Llegeix la documentació de l'API:

Revisa la secció d’endpoints disponibles. En un markdown, apunta com a mínim dos endpoints diferents.
Comprova si ofereix filtres o paràmetres opcionals interessants. En un markdown, anota’ls.
Verifica que la resposta sigui en format JSON (és el més adequat per a aquest exercici).

In [20]:
#Endpoint disponibles
response = requests.get('https://api.thedogapi.com/v1/breeds') 
response.json()

[{'weight': {'imperial': '6 - 13', 'metric': '3 - 6'},
  'height': {'imperial': '9 - 11.5', 'metric': '23 - 29'},
  'id': 1,
  'name': 'Affenpinscher',
  'bred_for': 'Small rodent hunting, lapdog',
  'breed_group': 'Toy',
  'life_span': '10 - 12 years',
  'temperament': 'Stubborn, Curious, Playful, Adventurous, Active, Fun-loving',
  'origin': 'Germany, France',
  'reference_image_id': 'BJa4kxc4X'},
 {'weight': {'imperial': '50 - 60', 'metric': '23 - 27'},
  'height': {'imperial': '25 - 27', 'metric': '64 - 69'},
  'id': 2,
  'name': 'Afghan Hound',
  'country_code': 'AG',
  'bred_for': 'Coursing and hunting',
  'breed_group': 'Hound',
  'life_span': '10 - 13 years',
  'temperament': 'Aloof, Clownish, Dignified, Independent, Happy',
  'origin': 'Afghanistan, Iran, Pakistan',
  'reference_image_id': 'hMyT4CDXR'},
 {'weight': {'imperial': '44 - 66', 'metric': '20 - 30'},
  'height': {'imperial': '30', 'metric': '76'},
  'id': 3,
  'name': 'African Hunting Dog',
  'bred_for': 'A wild pack animal',
  'life_span': '11 years',
  'temperament': 'Wild, Hardworking, Dutiful',
  'origin': '',
  'reference_image_id': 'rkiByec47'},
 {'weight': {'imperial': '40 - 65', 'metric': '18 - 29'},
  'height': {'imperial': '21 - 23', 'metric': '53 - 58'},
  'id': 4,
  'name': 'Airedale Terrier',
  'bred_for': 'Badger, otter hunting',
  'breed_group': 'Terrier',
  'life_span': '10 - 13 years',
  'temperament': 'Outgoing, Friendly, Alert, Confident, Intelligent, Courageous',
  'origin': 'United Kingdom, England',
  'reference_image_id': '1-7cgoZSh'},
 {'weight': {'imperial': '90 - 120', 'metric': '41 - 54'},
  'height': {'imperial': '28 - 34', 'metric': '71 - 86'},
  'id': 5,
  'name': 'Akbash Dog',
  'bred_for': 'Sheep guarding',
  'breed_group': 'Working',
  'life_span': '10 - 12 years',
  'temperament': 'Loyal, Independent, Intelligent, Brave',
  'origin': '',
  'reference_image_id': '26pHT3Qk7'},
 {'weight': {'imperial': '65 - 115', 'metric': '29 - 52'},
  'height': {'imperial': '24 - 28', 'metric': '61 - 71'},
  'id': 6,
  'name': 'Akita',
  'bred_for': 'Hunting bears',
  'breed_group': 'Working',
  'life_span': '10 - 14 years',
  'temperament': 'Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous',
  'reference_image_id': 'BFRYBufpm'},
 {'weight': {'imperial': '55 - 90', 'metric': '25 - 41'},
  'height': {'imperial': '18 - 24', 'metric': '46 - 61'},
  'id': 7,
  'name': 'Alapaha Blue Blood Bulldog',
  'description': "The Alapaha Blue Blood Bulldog is a well-developed, exaggerated bulldog with a broad head and natural drop ears. The prominent muzzle is covered by loose upper lips. The prominent eyes are set well apart. The Alapaha's coat is relatively short and fairly stiff. Preferred colors are blue merle, brown merle, or red merle all trimmed in white or chocolate and white. Also preferred are the glass eyes (blue) or marble eyes (brown and blue mixed in a single eye). The ears and tail are never trimmed or docked. The body is sturdy and very muscular. The well-muscled hips are narrower than the chest. The straight back is as long as the dog is high at the shoulders. The dewclaws are never removed and the feet are cat-like.",
  'bred_for': 'Guarding',
  'breed_group': 'Mixed',
  'life_span': '12 - 13 years',
  'history': '',
  'temperament': 'Loving, Protective, Trainable, Dutiful, Responsible',
  'reference_image_id': '33mJ-V3RX'},
 {'weight': {'imperial': '38 - 50', 'metric': '17 - 23'},
  'height': {'imperial': '23 - 26', 'metric': '58 - 66'},
  'id': 8,
  'name': 'Alaskan Husky',
  'bred_for': 'Sled pulling',
  'breed_group': 'Mixed',
  'life_span': '10 - 13 years',
  'temperament': 'Friendly, Energetic, Loyal, Gentle, Confident',
  'reference_image_id': '-HgpNnGXl'},
 {'weight': {'imperial': '65 - 100', 'metric': '29 - 45'},
  'height': {'imperial': '23 - 25', 'metric': '58 - 64'},
  'id': 9,
  'name': 'Alaskan Malamute',
  'bred_for': 'Hauling heavy freight, Sled pulling',
  'breed_group': 'Working',
  'life_span': '12 - 15 years',
  'temperament': 'Friendly, Affectionate, Devoted, Loyal, Dignified, Playful',
  'reference_image_id': 'dW5UucTIW'},
 {'weight': {'imperial': '60 - 120', 'metric': '27 - 54'},
  'height': {'imperial': '22 - 27', 'metric': '56 - 69'},
  'id': 10,
  'name': 'American Bulldog',
  'breed_group': 'Working',
  'life_span': '10 - 12 years',
  'temperament': 'Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant',
  'reference_image_id': 'pk1AAdloG'},
 {'weight': {'imperial': '30 - 150', 'metric': '14 - 68'},
  'height': {'imperial': '14 - 17', 'metric': '36 - 43'},
  'id': 11,
  'name': 'American Bully',
  'country_code': 'US',
  'bred_for': 'Family companion dog',
  'breed_group': '',
  'life_span': '8 – 15 years',
  'temperament': 'Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',
  'reference_image_id': 'sqQJDtbpY'},
 {'weight': {'imperial': '20 - 40', 'metric': '9 - 18'},
  'height': {'imperial': '15 - 19', 'metric': '38 - 48'},
  'id': 12,
  'name': 'American Eskimo Dog',
  'country_code': 'US',
  'bred_for': 'Circus performer',
  'breed_group': 'Non-Sporting',
  'life_span': '12 - 15 years',
  'temperament': 'Friendly, Alert, Reserved, Intelligent, Protective',
  'reference_image_id': 'Bymjyec4m'},
 {'weight': {'imperial': '7 - 10', 'metric': '3 - 5'},
  'height': {'imperial': '9 - 12', 'metric': '23 - 30'},
  'id': 13,
  'name': 'American Eskimo Dog (Miniature)',
  'country_code': 'US',
  'bred_for': 'Companionship',
  'life_span': '13 – 15 years',
  'temperament': 'Friendly, Alert, Reserved, Intelligent, Protective',
  'reference_image_id': '_gn8GLrE6'},
 {'weight': {'imperial': '65 - 75', 'metric': '29 - 34'},
  'height': {'imperial': '21 - 28', 'metric': '53 - 71'},
  'id': 14,
  'name': 'American Foxhound',
  'country_code': 'US',
  'bred_for': 'Fox hunting, scent hound',
  'breed_group': 'Hound',
  'life_span': '8 - 15 years',
  'temperament': 'Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving',
  'reference_image_id': 'S14n1x9NQ'},
 {'weight': {'imperial': '30 - 60', 'metric': '14 - 27'},
  'height': {'imperial': '17 - 21', 'metric': '43 - 53'},
  'id': 15,
  'name': 'American Pit Bull Terrier',
  'country_code': 'US',
  'bred_for': 'Fighting',
  'breed_group': 'Terrier',
  'life_span': '10 - 15 years',
  'temperament': 'Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',
  'reference_image_id': 'HkC31gcNm'},
 {'weight': {'imperial': '50 - 60', 'metric': '23 - 27'},
  'height': {'imperial': '17 - 19', 'metric': '43 - 48'},
  'id': 16,
  'name': 'American Staffordshire Terrier',
  'country_code': 'US',
  'bred_for': '',
  'breed_group': 'Terrier',
  'life_span': '12 - 15 years',
  'temperament': 'Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous',
  'reference_image_id': 'rJIakgc4m'},
 {'weight': {'imperial': '25 - 45', 'metric': '11 - 20'},
  'height': {'imperial': '15 - 18', 'metric': '38 - 46'},
  'id': 17,
  'name': 'American Water Spaniel',
  'country_code': 'US',
  'bred_for': 'Bird flushing and retrieving',
  'breed_group': 'Sporting',
  'life_span': '10 - 12 years',
  'temperament': 'Friendly, Energetic, Obedient, Intelligent, Protective, Trainable',
  'reference_image_id': 'SkmRJl9VQ'},
 {'weight': {'imperial': '80 - 150', 'metric': '36 - 68'},
  'height': {'imperial': '27 - 29', 'metric': '69 - 74'},
  'id': 18,
  'name': 'Anatolian Shepherd Dog',
  'bred_for': 'Livestock herding',
  'breed_group': 'Working',
  'life_span': '11 - 13 years',
  'temperament': 'Steady, Bold, Independent, Confident, Intelligent, Proud',
  'reference_image_id': 'BJT0Jx5Nm'},
 {'weight': {'imperial': '48 - 55', 'metric': '22 - 25'},
  'height': {'imperial': '20 - 22', 'metric': '51 - 56'},
  'id': 19,
  'name': 'Appenzeller Sennenhund',
  'bred_for': 'Herding livestock, pulling carts, and guarding the farm',
  'life_span': '12 – 14 years',
  'temperament': 'Reliable, Fearless, Energetic, Lively, Self-assured',
  'reference_image_id': 'HkNkxlqEX'},
 {'weight': {'imperial': '44 - 62', 'metric': '20 - 28'},
  'height': {'imperial': '17 - 20', 'metric': '43 - 51'},
  'id': 21,
  'name': 'Australian Cattle Dog',
  'country_code': 'AU',
  'bred_for': 'Cattle herding, herding trials',
  'breed_group': 'Herding',
  'life_span': '12 - 14 years',
  'temperament': 'Cautious, Energetic, Loyal, Obedient, Protective, Brave',
  'reference_image_id': 'IBkYVm4v1'},
 {'weight': {'imperial': '31 - 46', 'metric': '14 - 21'},
  'height': {'imperial': '17 - 20', 'metric': '43 - 51'},
  'id': 22,
  'name': 'Australian Kelpie',
  'country_code': 'AU',
  'bred_for': 'Farm dog, Cattle herding',
  'breed_group': 'Herding',
  'life_span': '10 - 13 years',
  'temperament': 'Friendly, Energetic, Alert, Loyal, Intelligent, Eager',
  'reference_image_id': 'Hyq1ge9VQ'},
 {'weight': {'imperial': '35 - 65', 'metric': '16 - 29'},
  'height': {'imperial': '18 - 23', 'metric': '46 - 58'},
  'id': 23,
  'name': 'Australian Shepherd',
  'country_code': 'AU',
  'bred_for': 'Sheep herding',
  'breed_group': 'Herding',
  'life_span': '12 - 16 years',
  'temperament': 'Good-natured, Affectionate, Intelligent, Active, Protective',
  'reference_image_id': 'B1-llgq4m'},
 {'weight': {'imperial': '14 - 16', 'metric': '6 - 7'},
  'height': {'imperial': '10 - 11', 'metric': '25 - 28'},
  'id': 24,
  'name': 'Australian Terrier',
  'country_code': 'AU',
  'bred_for': 'Cattle herdering, hunting snakes and rodents',
  'breed_group': 'Terrier',
  'life_span': '15 years',
  'temperament': 'Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous',
  'reference_image_id': 'r1Ylge5Vm'},
 {'weight': {'imperial': '33 - 55', 'metric': '15 - 25'},
  'height': {'imperial': '23 - 29', 'metric': '58 - 74'},
  'id': 25,
  'name': 'Azawakh',
  'bred_for': 'Livestock guardian, hunting',
  'breed_group': 'Hound',
  'life_span': '10 - 13 years',
  'temperament': 'Aloof, Affectionate, Attentive, Rugged, Fierce, Refined',
  'reference_image_id': 'SkvZgx94m'},
 {'weight': {'imperial': '40 - 65', 'metric': '18 - 29'},
  'height': {'imperial': '20 - 26', 'metric': '51 - 66'},
  'id': 26,
  'name': 'Barbet',
  'bred_for': 'Hunting water game',
  'life_span': '13 – 15 years',
  'temperament': 'Obedient, Companionable, Intelligent, Joyful',
  'reference_image_id': 'HyWGexcVQ'},
 {'weight': {'imperial': '22 - 24', 'metric': '10 - 11'},
  'height': {'imperial': '16 - 17', 'metric': '41 - 43'},
  'id': 28,
  'name': 'Basenji',
  'bred_for': 'Hunting',
  'breed_group': 'Hound',
  'life_span': '10 - 12 years',
  'temperament': 'Affectionate, Energetic, Alert, Curious, Playful, Intelligent',
  'reference_image_id': 'H1dGlxqNQ'},
 {'weight': {'imperial': '35 - 40', 'metric': '16 - 18'},
  'height': {'imperial': '13 - 15', 'metric': '33 - 38'},
  'id': 29,
  'name': 'Basset Bleu de Gascogne',
  'bred_for': 'Hunting on foot.',
  'breed_group': 'Hound',
  'life_span': '10 - 14 years',
  'temperament': 'Affectionate, Lively, Agile, Curious, Happy, Active',
  'reference_image_id': 'BkMQll94X'},
 {'weight': {'imperial': '50 - 65', 'metric': '23 - 29'},
  'height': {'imperial': '14', 'metric': '36'},
  'id': 30,
  'name': 'Basset Hound',
  'bred_for': 'Hunting by scent',
  'breed_group': 'Hound',
  'life_span': '12 - 15 years',
  'temperament': 'Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle',
  'reference_image_id': 'Sy57xx9EX'},
 {'weight': {'imperial': '20 - 35', 'metric': '9 - 16'},
  'height': {'imperial': '13 - 15', 'metric': '33 - 38'},
  'id': 31,
  'name': 'Beagle',
  'bred_for': 'Rabbit, hare hunting',
  'breed_group': 'Hound',
  'life_span': '13 - 16 years',
  'temperament': 'Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent',
  'reference_image_id': 'Syd4xxqEm'},
 {'weight': {'imperial': '45 - 55', 'metric': '20 - 25'},
  'height': {'imperial': '20 - 22', 'metric': '51 - 56'},
  'id': 32,
  'name': 'Bearded Collie',
  'bred_for': 'Sheep herding',
  'breed_group': 'Herding',
  'life_span': '12 - 14 years',
  'temperament': 'Self-confidence, Hardy, Lively, Alert, Intelligent, Active',
  'reference_image_id': 'A09F4c1qP'},
 {'weight': {'imperial': '80 - 110', 'metric': '36 - 50'},
  'height': {'imperial': '24 - 27.5', 'metric': '61 - 70'},
  'id': 33,
  'name': 'Beauceron',
  'bred_for': 'Boar herding, hunting, guarding',
  'breed_group': 'Herding',
  'life_span': '10 - 12 years',
  'temperament': 'Fearless, Friendly, Intelligent, Protective, Calm',
  'reference_image_id': 'HJQ8ge5V7'},
 {'weight': {'imperial': '17 - 23', 'metric': '8 - 10'},
  'height': {'imperial': '15 - 16', 'metric': '38 - 41'},
  'id': 34,
  'name': 'Bedlington Terrier',
  'bred_for': 'Killing rat, badger, other vermin',
  'breed_group': 'Terrier',
  'life_span': '14 - 16 years',
  'temperament': 'Affectionate, Spirited, Intelligent, Good-tempered',
  'reference_image_id': 'ByK8gx947'},
 {'weight': {'imperial': '40 - 80', 'metric': '18 - 36'},
  'height': {'imperial': '22 - 26', 'metric': '56 - 66'},
  'id': 36,
  'name': 'Belgian Malinois',
  'bred_for': 'Stock herding',
  'breed_group': 'Herding',
  'life_span': '12 - 14 years',
  'temperament': 'Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective',
  'reference_image_id': 'r1f_ll5VX'},
 {'weight': {'imperial': '40 - 65', 'metric': '18 - 29'},
  'height': {'imperial': '22 - 26', 'metric': '56 - 66'},
  'id': 38,
  'name': 'Belgian Tervuren',
  'bred_for': 'Guarding, Drafting, Police work.',
  'breed_group': 'Herding',
  'life_span': '10 - 12 years',
  'temperament': 'Energetic, Alert, Loyal, Intelligent, Attentive, Protective',
  'reference_image_id': 'B1KdxlcNX'},
 {'weight': {'imperial': '65 - 120', 'metric': '29 - 54'},
  'height': {'imperial': '23 - 27.5', 'metric': '58 - 70'},
  'id': 41,
  'name': 'Bernese Mountain Dog',
  'bred_for': 'Draft work',
  'breed_group': 'Working',
  'life_span': '7 - 10 years',
  'temperament': 'Affectionate, Loyal, Intelligent, Faithful',
  'reference_image_id': 'S1fFlx5Em'},
 {'weight': {'imperial': '10 - 18', 'metric': '5 - 8'},
  'height': {'imperial': '9.5 - 11.5', 'metric': '24 - 29'},
  'id': 42,
  'name': 'Bichon Frise',
  'bred_for': 'Companion',
  'breed_group': 'Non-Sporting',
  'life_span': '15 years',
  'temperament': 'Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive',
  'reference_image_id': 'HkuYlxqEQ'},
 {'weight': {'imperial': '65 - 100', 'metric': '29 - 45'},
  'height': {'imperial': '23 - 27', 'metric': '58 - 69'},
  'id': 43,
  'name': 'Black and Tan Coonhound',
  'bred_for': 'Hunting raccoons, night hunting',
  'breed_group': 'Hound',
  'life_span': '10 - 12 years',
  'temperament': 'Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable',
  'reference_image_id': 'HJAFgxcNQ'},
 {'weight': {'imperial': '80 - 110', 'metric': '36 - 50'},
  'height': {'imperial': '23 - 27', 'metric': '58 - 69'},
  'id': 45,
  'name': 'Bloodhound',
  'bred_for': 'Trailing',
  'breed_group': 'Hound',
  'life_span': '8 - 10 years',
  'temperament': 'Stubborn, Affectionate, Gentle, Even Tempered',
  'reference_image_id': 'Skdcgx9VX'},
 {'weight': {'imperial': '45 - 80', 'metric': '20 - 36'},
  'height': {'imperial': '21 - 27', 'metric': '53 - 69'},
  'id': 47,
  'name': 'Bluetick Coonhound',
  'bred_for': 'Hunting with a superior sense of smell.',
  'breed_group': 'Hound',
  'life_span': '12 - 14 years',
  'temperament': 'Friendly, Intelligent, Active',
  'reference_image_id': 'rJxieg9VQ'},
 {'weight': {'imperial': '110 - 200', 'metric': '50 - 91'},
  'height': {'imperial': '22 - 27', 'metric': '56 - 69'},
  'id': 48,
  'name': 'Boerboel',
  'bred_for': 'Guarding the homestead, farm work.',
  'breed_group': 'Working',
  'life_span': '10 - 12 years',
  'temperament': 'Obedient, Confident, Intelligent, Dominant, Territorial',
  'reference_image_id': 'HyOjge5Vm'},
 {'weight': {'imperial': '30 - 45', 'metric': '14 - 20'},
  'height': {'imperial': '18 - 22', 'metric': '46 - 56'},
  'id': 50,
  'name': 'Border Collie',
  'bred_for': 'Sheep herder',
  'breed_group': 'Herding',
  'life_span': '12 - 16 years',
  'temperament': 'Tenacious, Keen, Energetic, Responsive, Alert, Intelligent',
  'reference_image_id': 'sGQvQUpsp'},
 {'weight': {'imperial': '11.5 - 15.5', 'metric': '5 - 7'},
  'height': {'imperial': '11 - 16', 'metric': '28 - 41'},
  'id': 51,
  'name': 'Border Terrier',
  'bred_for': 'Fox bolting, ratting',
  'breed_group': 'Terrier',
  'life_span': '12 - 14 years',
  'temperament': 'Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered',
  'reference_image_id': 'HJOpge9Em'},
 {'weight': {'imperial': '10 - 25', 'metric': '5 - 11'},
  'height': {'imperial': '16 - 17', 'metric': '41 - 43'},
  'id': 53,
  'name': 'Boston Terrier',
  'bred_for': 'Ratting, Companionship',
  'breed_group': 'Non-Sporting',
  'life_span': '11 - 13 years',
  'temperament': 'Friendly, Lively, Intelligent',
  'reference_image_id': 'rkZRggqVX'},
 {'weight': {'imperial': '70 - 110', 'metric': '32 - 50'},
  'height': {'imperial': '23.5 - 27.5', 'metric': '60 - 70'},
  'id': 54,
  'name': 'Bouvier des Flandres',
  'bred_for': 'Cattle herding',
  'breed_group': 'Herding',
  'life_span': '10 - 15 years',
  'temperament': 'Protective, Loyal, Gentle, Intelligent, Familial, Rational',
  'reference_image_id': 'Byd0xl5VX'},
 {'weight': {'imperial': '50 - 70', 'metric': '23 - 32'},
  'height': {'imperial': '21.5 - 25', 'metric': '55 - 64'},
  'id': 55,
  'name': 'Boxer',
  'bred_for': 'Bull-baiting, guardian',
  'breed_group': 'Working',
  'life_span': '8 - 10 years',
  'temperament': 'Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm',
  'reference_image_id': 'ry1kWe5VQ'},
 {'weight': {'imperial': '25 - 40', 'metric': '11 - 18'},
  'height': {'imperial': '14 - 18', 'metric': '36 - 46'},
  'id': 56,
  'name': 'Boykin Spaniel',
  'bred_for': 'Turkey retrieving',
  'breed_group': 'Sporting',
  'life_span': '10 - 14 years',
  'temperament': 'Friendly, Energetic, Companionable, Intelligent, Eager, Trainable',
  'reference_image_id': 'ryHJZlcNX'},
 {'weight': {'imperial': '55 - 88', 'metric': '25 - 40'},
  'height': {'imperial': '21.5 - 26.5', 'metric': '55 - 67'},
  'id': 57,
  'name': 'Bracco Italiano',
  'bred_for': 'Versatile gun dog',
  'breed_group': 'Sporting',
  'life_span': '10 - 12 years',
  'temperament': 'Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable',
  'reference_image_id': 'S13yZg5VQ'},
 {'weight': {'imperial': '70 - 90', 'metric': '32 - 41'},
  'height': {'imperial': '22 - 27', 'metric': '56 - 69'},
  'id': 58,
  'name': 'Briard',
  'bred_for': 'Herding, guarding sheep',
  'breed_group': 'Herding',
  'life_span': '10 - 12 years',
  'temperament': 'Fearless, Loyal, Obedient, Intelligent, Faithful, Protective',
  'reference_image_id': 'rkVlblcEQ'},
 {'weight': {'imperial': '30 - 45', 'metric': '14 - 20'},
  'height': {'imperial': '17.5 - 20.5', 'metric': '44 - 52'},
  'id': 59,
  'name': 'Brittany',
  'bred_for': 'Pointing, retrieving',
  'breed_group': 'Sporting',
  'life_span': '12 - 14 years',
  'temperament': 'Agile, Adaptable, Quick, Intelligent, Attentive, Happy',
  'reference_image_id': 'HJWZZxc4X'},
 {'weight': {'imperial': '50 - 70', 'metric': '23 - 32'},
  'height': {'imperial': '21 - 22', 'metric': '53 - 56'},
  'id': 61,
  'name': 'Bull Terrier',
  'bred_for': 'Bull baiting, Fighting',
  'breed_group': 'Terrier',
  'life_span': '10 - 12 years',
  'temperament': 'Trainable, Protective, Sweet-Tempered, Keen, Active',
  'reference_image_id': 'VSraIEQGd'},
 {'weight': {'imperial': '25 - 33', 'metric': '11 - 15'},
  'height': {'imperial': '10 - 14', 'metric': '25 - 36'},
  'id': 62,
  'name': 'Bull Terrier (Miniature)',
  'bred_for': "An elegant man's fashion statement",
  'life_span': '11 – 14 years',
  'temperament': 'Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial',

3. Fes una petició GET senzilla:

Mostra el codi d'estat de la resposta.
Imprimeix de forma clara alguns dels camps de la resposta JSON.

In [22]:
#Realizar una petición GET - Using a public API that returns JSON
url = "https://api.thedogapi.com/v1/breeds"
response = requests.get(url)

# Mostrar el código de estado
print(f"Código de estado: {response.status_code}")

# Verificar si la respuesta es JSON antes de parsear
if response.status_code == 200:
	try:
		data = response.json()
		# Imprimir algunos campos de la respuesta
		print(f"\nTotal de razas de perros: {len(data)}")
		print("\nPrimeras 3 razas:")
		for breed in data[:3]:
			print(f"  - Nombre: {breed.get('name', 'N/A')}")
			print(f"    Origen: {breed.get('origin', 'N/A')}")
			print(f"    Temperamento: {breed.get('temperament', 'N/A')}\n")
	except requests.exceptions.JSONDecodeError:
		print("Error: La respuesta no es JSON válido")
		print(response.text[:200])
else:
	print(f"Error en la petición: {response.status_code}")

Código de estado: 200

Total de razas de perros: 172

Primeras 3 razas:
  - Nombre: Affenpinscher
    Origen: Germany, France
    Temperamento: Stubborn, Curious, Playful, Adventurous, Active, Fun-loving

  - Nombre: Afghan Hound
    Origen: Afghanistan, Iran, Pakistan
    Temperamento: Aloof, Clownish, Dignified, Independent, Happy

  - Nombre: African Hunting Dog
    Origen:
    Temperamento: Wild, Hardworking, Dutiful

4. Converteix les dades a un DataFrame de pandas:

Mostra les primeres files del DataFrame.

In [25]:
import pandas as pd

dogs = pd.DataFrame(response.json())
dogs.head()

,weight,height,id,name,bred_for,breed_group,life_span,temperament,origin,reference_image_id,country_code,description,history
0,"{'imperial': '6 - 13', 'metric': '3 - 6'}","{'imperial': '9 - 11.5', 'metric': '23 - 29'}",1,Affenpinscher,"Small rodent hunting, lapdog",Toy,10 - 12 years,"Stubborn, Curious, Playful, Adventurous, Activ...","Germany, France",BJa4kxc4X,NaN,NaN,NaN
1,"{'imperial': '50 - 60', 'metric': '23 - 27'}","{'imperial': '25 - 27', 'metric': '64 - 69'}",2,Afghan Hound,Coursing and hunting,Hound,10 - 13 years,"Aloof, Clownish, Dignified, Independent, Happy","Afghanistan, Iran, Pakistan",hMyT4CDXR,AG,NaN,NaN
2,"{'imperial': '44 - 66', 'metric': '20 - 30'}","{'imperial': '30', 'metric': '76'}",3,African Hunting Dog,A wild pack animal,NaN,11 years,"Wild, Hardworking, Dutiful",,rkiByec47,NaN,NaN,NaN
3,"{'imperial': '40 - 65', 'metric': '18 - 29'}","{'imperial': '21 - 23', 'metric': '53 - 58'}",4,Airedale Terrier,"Badger, otter hunting",Terrier,10 - 13 years,"Outgoing, Friendly, Alert, Confident, Intellig...","United Kingdom, England",1-7cgoZSh,NaN,NaN,NaN
4,"{'imperial': '90 - 120', 'metric': '41 - 54'}","{'imperial': '28 - 34', 'metric': '71 - 86'}",5,Akbash Dog,Sheep guarding,Working,10 - 12 years,"Loyal, Independent, Intelligent, Brave",,26pHT3Qk7,NaN,NaN,NaN

---------------------------------------------------------------------------------------------------------------------

### Nivell 3

1. Utilitza l’API d’Open Data BCN per:

Cercar un dataset del teu interès mitjançant package_search i package_show.

In [22]:
import requests
response = requests.get('https://opendata-ajuntament.barcelona.cat/data/api/action/package_search')
response.json()

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_search',
 'success': True,
 'result': {'count': 552,
  'sort': 'fecha_publicacion desc',
  'facets': {},
  'results': [{'notes_translated': {'ca': 'Rebuts i quota del padró de la Taxa de Guals de l’Ajuntament de Barcelona per dimensió i categoria fiscal del carrer. La taxa grava l’ús restringit de la via pública (vorera) per l’entrada i sortida de\r\nvehicles dels edificis. No inclou les liquidacions emeses posteriors a la publicació del padró',
     'en': 'Receipts and quota of the register of the Vados Tax of the Barcelona City Council by dimension and fiscal category of the street. The fee is levied on the restricted use of the public thoroughfare (sidewalk) for the entrance and exit of buildings vehicles',
     'es': 'Recibos y cuota del padrón de la Tasa de Vados del Ayuntamiento de Barcelona por dimensión y categoría fiscal de la calle. La tasa grava el uso restringido de la vía pública (acera) por la entrada y salida de\r\nvehículos de los edificios. No incluye las liquidaciones posteriores a la emisión del padrón.'},
    'geolocation': 'No',
    'dades_alt_valor': 'No',
    'url_tornada': {'ca': 'https://ajuntament.barcelona.cat/hisenda/ca/tramits-gestions/taxa-de-guals?profile=1',
     'en': 'https://ajuntament.barcelona.cat/hisenda/en/procedures-payments/driveway-tax?profile=1',
     'es': 'https://ajuntament.barcelona.cat/hisenda/es/tramites-gestiones/tasa-de-vados'},
    'dataset_fields_description': '',
    'fuente': 'Ajuntament de Barcelona',
    'tag': 'Rebuts,Quota,Impost,Guals,Any 2025,Any 2024,Padró taxa guals',
    'private': False,
    'num_tags': 7,
    'code': 'rebuts-quota-padro-guals',
    'frequency': 'ANUAL',
    'id': '7e63eeb0-670a-4bcc-bee9-1d89697a4501',
    'title_translated': {'ca': 'Rebuts i quota del padró de la  Taxa de Guals de l’Ajuntament de Barcelona',
     'en': 'Receipts and quota of the register of the Vados Tax of the Barcelona City Council',
     'es': 'Recibos y cuota del padrón de la Tasa de Vados del Ayuntamiento de Barcelona'},
    'metadata_modified': '2025-10-29T07:01:43.660727',
    'author': 'Gerència d’Àrea de Economia, Recursos i Promoció Econòmica',
    'author_email': None,
    'isopen': True,
    'long_format': 'No',
    'state': 'active',
    'version': '',
    'mar_od': 'No',
    'relationships_as_object': [],
    'department': 'Institut Municipal d’Hisenda – Departament de Bases de Dades i Secretaria Tècnica',
    'creator_user_id': '6d593275-d059-4261-9004-e6df8677e3bf',
    'type': 'dataset',
    'resources': [{'api_access_number_absolute': '1',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': '7e63eeb0-670a-4bcc-bee9-1d89697a4501',
      'datastore_active': True,
      'id': 'e35dce7d-96f6-4130-b794-42967da2cce5',
      'description': '',
      'state': 'active',
      'api_access_number': '1',
      'size': '10295',
      'token_required': '',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '10',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': '',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2025_rebuts_quota_guals_BCN.csv',
      'created': '2025-10-16T11:08:02.009845',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/7e63eeb0-670a-4bcc-bee9-1d89697a4501/resource/e35dce7d-96f6-4130-b794-42967da2cce5/download',
      'downloads_absolute': '11',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-11-10T02:12:26.515326\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-10-17T02:12:53.348061\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2025-10-16T11:08:01.899666',
      'position': 0,
      'revision_id': '8d018255-c15c-4cd4-b427-aeedf3b50404',
      'resource_type': None},
     {'api_access_number_absolute': '1',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': '7e63eeb0-670a-4bcc-bee9-1d89697a4501',
      'datastore_active': True,
      'id': '5f5e606d-4a38-4b4a-a16a-38e024e0b642',
      'description': '',
      'state': 'active',
      'api_access_number': '1',
      'size': '10294',
      'token_required': '',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '2',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': '',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2024_rebuts_quota_guals_BCN.csv',
      'created': '2025-10-16T10:14:31.153191',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/7e63eeb0-670a-4bcc-bee9-1d89697a4501/resource/5f5e606d-4a38-4b4a-a16a-38e024e0b642/download',
      'downloads_absolute': '2',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-11-10T02:12:26.533776\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-10-17T02:12:53.326117\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2025-10-16T10:14:31.058436',
      'position': 1,
      'revision_id': '8d018255-c15c-4cd4-b427-aeedf3b50404',
      'resource_type': None}],
    'token_required': 'No',
    'decalatgeNum': 'N/A',
    'tags': [{'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2024',
      'id': '283fc2f8-cbae-4ef0-9884-edf991193b9f',
      'name': 'Any 2024'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2025',
      'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
      'name': 'Any 2025'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Guals',
      'id': 'b88e1552-8bb0-4ba7-b4ad-0c09d4eb2be0',
      'name': 'Guals'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Impost',
      'id': '28e97e18-f972-4275-bc7d-3100c8860a7f',
      'name': 'Impost'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Padró taxa guals',
      'id': 'e48f8ba6-7fe5-459f-9a31-2a28f80eca8c',
      'name': 'Padró taxa guals'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Quota',
      'id': '2637cfb2-4663-4fd9-a3b6-cc823b611d51',
      'name': 'Quota'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Rebuts',
      'id': 'f4272c98-a4fc-4376-82a4-bd3e721906ad',
      'name': 'Rebuts'}],
    'ODS_Principal_agenda_2030': 'ODS 16: Pau, justícia i institucions sòlides',
    'fecha_publicacion': '2025-10-29',
    'ODS_Colateral2_agenda_2030': 'N/A',
    'ODS_Colateral1_agenda_2030': 'N/A',
    'license_id': 'CC-BY-4.0',
    'hide_url': 'No',
    'relationships_as_subject': [],
    'license_title': 'Creative Commons Attribution 4.0',
    'groups': [],
    'num_resources': 2,
    'organization': {'code': 'sector-public',
     'display_name': 'Sector públic',
     'description': 'Public sector',
     'parent': {'code': 'administracio',
      'display_name': 'Administració',
      'description': 'Administration',
      'created': '2017-01-24T16:55:08.456934',
      'package_count': 0,
      'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-ajuntament',
      'description_translated': {'ca': 'Administració',
       'en': 'Administration',
       'es': 'Administración'},
      'name': 'administracio',
      'is_organization': True,
      'state': 'active',
      'image_url': 'bcn-icon-ajuntament',
      'groups': [],
      'type': 'organization',
      'title': 'Administration',
      'revision_id': 'a22b23c4-21e9-4e5f-9d8c-0b2c7ee32f63',
      'title_translated': {'ca': 'Administració',
       'en': 'Administration',
       'es': 'Administración'},
      'num_followers': 0,
      'id': '2e792c19-83e2-4ef2-a643-9b9d0360c402',
      'approval_status': 'approved'},
     'created': '2017-01-24T16:55:06.806043',
     'package_count': 91,
     'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-punts-registre',
     'tematica_nti': 'sector-publico',
     'description_translated': {'ca': 'Sector públic',
      'en': 'Public sector',
      'es': 'Sector público'},
     'name': 'sector-public',
     'is_organization': True,
     'state': 'active',
     'image_url': 'bcn-icon-punts-registre',
     'groups': [{'capacity': 'public', 'name': 'administracio'}],
     'type': 'organization',
     'title': 'Public sector',
     'revision_id': '42a96f79-3356-4692-ad4a-923d811b8a9f',
     'title_translated': {'ca': 'Sector públic',
      'en': 'Public sector',
      'es': 'Sector público'},
     'num_followers': 0,
     'id': '5a597816-bbe2-4174-bf69-53644330bb5f',
     'approval_status': 'approved'},
    'name': 'rebuts-quota-padro-guals',
    'url': None,
    'notes': 'Receipts and quota of the register of the Vados Tax of the Barcelona City Council by dimension and fiscal category of the street. The fee is levied on the restricted use of the public thoroughfare (sidewalk) for the entrance and exit of buildings vehicles',
    'owner_org': '5a597816-bbe2-4174-bf69-53644330bb5f',
    'load_type': 'ds_manual',
    'api': 'Yes',
    'license_url': 'https://creativecommons.org/licenses/by/4.0/',
    'historical': 'Yes',
    'title': 'Receipts and quota of the register of the Vados Tax of the Barcelona City Council',
    'revision_id': 'bc5f0268-cc97-4091-ac51-ac59ad6fa1fa',
    'extras': [{'key': '01.Codi_Districte', 'value': 'Codi del districte'},
     {'key': '02.Nom_Districte', 'value': 'Nom del districte'},
     {'key': '03.Categoria_Fiscal_Carrer',
      'value': 'Categoria fiscal del carrer'},
     {'key': '04.Metres', 'value': 'Metres quadrats del gual'},
     {'key': '05.Total_Rebuts', 'value': '\t Nombre total de rebuts emesos'},
     {'key': '06.Total_Quota', 'value': 'Total de la quota en €'}]},
   {'notes_translated': {'ca': 'Rebuts i quota del padró de l’Impost de vehicles de tracció mecànica de l’Ajuntament de Barcelona. No inclou les liquidacions emeses posteriors a la publicació del padró.',
     'en': 'Receipts and quota of the vehicle excise tax register from the Barcelona City Council. Settlements issued after the publication of the tax roll are not included.',
     'es': 'Recibos y cuota del padrón del Impuesto sobre vehículos de tracción mecánica del Ayuntamiento de Barcelona. No se incluyen las liquidaciones emitidas posteriores a la publicación del padrón.'},
    'geolocation': 'No',
    'dades_alt_valor': 'Geoespacial',
    'url_tornada': {'ca': 'https://ajuntament.barcelona.cat/hisenda/ca/tramits-gestions/ivtm-impost-sobre-vehicles-de-traccio-mecanica?profile=1',
     'en': 'https://ajuntament.barcelona.cat/hisenda/en/procedures-payments/ivtm?profile=1',
     'es': 'https://ajuntament.barcelona.cat/hisenda/es/tramites-gestiones/ivtm-impuesto-sobre-vehiculos-de-traccion-mecanica?profile=1'},
    'dataset_fields_description': '',
    'fuente': 'Ajuntament de Barcelona',
    'tag': 'Impost,Quota,Rebuts,Vehicles,IVTM,Any 2025',
    'private': False,
    'num_tags': 6,
    'code': 'rebuts-quota-padro-vehicle-bcn',
    'frequency': 'ANUAL',
    'id': 'e21b436f-7f84-4f7b-a3de-f7dc6b43264f',
    'title_translated': {'ca': 'Rebuts i quota del padró de l’Impost de vehicles de tracció mecànica de l’Ajuntament de Barcelona',
     'en': 'Receipts and charges from the motor vehicle tax roll of the Barcelona City Council',
     'es': 'Recibos y cuota del padrón del Impuesto de vehículos de tracción mecánica del Ayuntamiento de Barcelona'},
    'metadata_modified': '2025-10-28T07:36:42.984096',
    'author': 'Gerència d’Àrea d’Economia, Recursos i Promoció econòmica',
    'author_email': None,
    'isopen': True,
    'long_format': 'No',
    'state': 'active',
    'version': '',
    'mar_od': 'No',
    'relationships_as_object': [],
    'department': 'Institut Municipal d’Hisenda – Departament de Bases de Dades i Secretaria Tècnica',
    'creator_user_id': '9a1528df-3413-4449-a875-638d55f91982',
    'type': 'dataset',
    'resources': [{'api_access_number_absolute': '3',
      'cache_last_updated': None,
      'incorporated_in_cityos_res': 'No',
      'token_type': '',
      'package_id': 'e21b436f-7f84-4f7b-a3de-f7dc6b43264f',
      'datastore_active': True,
      'id': '110749d9-ee3e-4d1f-b962-680e3cebe608',
      'description': '',
      'state': 'active',
      'api_access_number': '3',
      'size': '22505',
      'token_required': '',
      'hash': '',
      'token_name': '',
      'format': 'CSV',
      'downloads': '41',
      'mimetype_inner': None,
      'url_type': 'upload',
      'token_provider': '',
      'column_types': '',
      'hide_url': '',
      'token_version': '',
      'mimetype': None,
      'cache_url': None,
      'name': '2025_rebuts_quota_padro_vehicles_BCN.csv',
      'created': '2025-08-28T12:50:42.010954',
      'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/e21b436f-7f84-4f7b-a3de-f7dc6b43264f/resource/110749d9-ee3e-4d1f-b962-680e3cebe608/download',
      'downloads_absolute': '60',
      'map_visualization_res': 'none',
      'qa': '{\'updated\': \'2025-11-10T02:12:28.726448\', \'openness_score\': 3, \'archival_timestamp\': None, \'format\': u\'CSV\', \'created\': \'2025-08-29T02:12:02.288172\', \'resource_timestamp\': None, \'openness_score_reason\': u\'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.\'}',
      'last_modified': '2025-08-28T12:50:41.921244',
      'position': 0,
      'revision_id': '69522716-0f80-4cea-8e5b-8b0b6fdd00e3',
      'resource_type': None}],
    'token_required': 'No',
    'decalatgeNum': 'N/A',
    'tags': [{'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Any 2025',
      'id': '0510e622-4b6e-4f59-994f-41c01b0a8b1f',
      'name': 'Any 2025'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'IVTM',
      'id': '43b59ad2-4302-42a9-bbbd-a128e67bc135',
      'name': 'IVTM'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Impost',
      'id': '28e97e18-f972-4275-bc7d-3100c8860a7f',
      'name': 'Impost'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Quota',
      'id': '2637cfb2-4663-4fd9-a3b6-cc823b611d51',
      'name': 'Quota'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Rebuts',
      'id': 'f4272c98-a4fc-4376-82a4-bd3e721906ad',
      'name': 'Rebuts'},
     {'vocabulary_id': None,
      'state': 'active',
      'display_name': 'Vehicles',
      'id': '64f8342a-4609-4523-a18e-4c2e387afdfc',
      'name': 'Vehicles'}],
    'ODS_Principal_agenda_2030': 'ODS 16: Pau, justícia i institucions sòlides',
    'fecha_publicacion': '2025-09-09',
    'ODS_Colateral2_agenda_2030': 'N/A',
    'ODS_Colateral1_agenda_2030': 'N/A',
    'license_id': 'CC-BY-4.0',
    'hide_url': 'No',
    'relationships_as_subject': [],
    'license_title': 'Creative Commons Attribution 4.0',
    'groups': [],
    'num_resources': 1,
    'organization': {'code': 'sector-public',
     'display_name': 'Sector públic',
     'description': 'Public sector',
     'parent': {'code': 'administracio',
      'display_name': 'Administració',
      'description': 'Administration',
      'created': '2017-01-24T16:55:08.456934',
      'package_count': 0,
      'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-ajuntament',
      'description_translated': {'ca': 'Administració',
       'en': 'Administration',
       'es': 'Administración'},
      'name': 'administracio',
      'is_organization': True,
      'state': 'active',
      'image_url': 'bcn-icon-ajuntament',
      'groups': [],
      'type': 'organization',
      'title': 'Administration',
      'revision_id': 'a22b23c4-21e9-4e5f-9d8c-0b2c7ee32f63',
      'title_translated': {'ca': 'Administració',
       'en': 'Administration',
       'es': 'Administración'},
      'num_followers': 0,
      'id': '2e792c19-83e2-4ef2-a643-9b9d0360c402',
      'approval_status': 'approved'},
     'created': '2017-01-24T16:55:06.806043',
     'package_count': 91,
     'image_display_url': 'https://opendata-ajuntament.barcelona.cat/data/uploads/group/bcn-icon-punts-registre',
     'tematica_nti': 'sector-publico',
     'description_translated': {'ca': 'Sector públic',
      'en': 'Public sector',
      'es': 'Sector público'},
     'name': 'sector-public',
     'is_organization': True,
     'state': 'active',
     'image_url': 'bcn-icon-punts-registre',
     'groups': [{'capacity': 'public', 'name': 'administracio'}],
     'type': 'organization',
     'title': 'Public sector',
     'revision_id': '42a96f79-3356-4692-ad4a-923d811b8a9f',
     'title_translated': {'ca': 'Sector públic',
      'en': 'Public sector',
      'es': 'Sector público'},
     'num_followers': 0,
     'id': '5a597816-bbe2-4174-bf69-53644330bb5f',
     'approval_status': 'approved'},
    'name': 'rebuts-quota-padro-vehicle-bcn',
    'url': None,
    'notes': 'Receipts and quota of the vehicle excise tax register from the Barcelona City Council. Settlements issued after the publication of the tax roll are not included.',
    'owner_org': '5a597816-bbe2-4174-bf69-53644330bb5f',
    'load_type': 'ds_manual',
    'api': 'Yes',
    'license_url': 'https://creativecommons.org/licenses/by/4.0/',
    'historical': 'Yes',
    'title': 'Receipts and charges from the motor vehicle tax roll of the Barcelona City Council',
    'revision_id': '86f63e1d-71b6-42b4-bd8b-e25ffb09695d',
    'extras': [{'key': '01.Codi_Districte', 'value': 'Codi del districte'},
     {'key': '02.Nom_Districte', 'value': 'Nom del districte'},
     {'key': '03.Classe_Vehicle',
      'value': "Tipus de vehicle segons l'ordenança de l’impost"},
     {'key': '04.Classificacio_Ordenança',
      'value': "Desglossament de la classe de vehicle en funció de les seves característiques ( Potencia, càrrega, places, cilindrada) segons l'ordenança"},
     {'key': '05.Total_Rebuts', 'value': 'Nombre total de rebuts emesos'},
     {'key': '06.Total_Quota', 'value': 'Total de la quota en €'}]},
   {'notes_translated': {'ca': "Nombre de persones immigrants a Barcelona per any segons el Padró Municipal d'Habitants",
     'en': 'Number of immigrant people in Barcelona by year by the Municipal Register of Inhabitants',
     'es': 'Número de personas inmigrantes en Barcelona por año según el Padrón Municipal de Habitantes'},
    'geolocation': 'No',
    'code': 'pad_imm_mdbas',
    'url_tornada': {'ca': '', 'en': '', 'es': ''},
    'dataset_fields_description': 'Les dades dels fluxos padronals estan sotmeses a rectificacions d’acord amb els registres oficials. A partir de 2005 s’homogeneïtzen els criteris de recomptes de les entrades per immigració. Si la dada és menor que 5 s’indica com ‘..’.. Si la dada és menor que 5, s’indica com ‘’..’’',
    'fuente': "Ajuntament de Barcelona. Oficina Municipal de Dades (OMD). Padró Municipal d'Habitants",
    'private': False,
    'num_tags': 30,
    'api': 'Yes',
    'frequency': 'ANUAL',
    'id': '778e5885-5bdb-416e-adbd-854632381ad1',
    'title_translated': {'ca': 'Persones immigrants',
     'en': 'Immigrants',
     'es': 'Personas inmigrantes'},
    'metadata_modified': '2025-07-24T08:29:47.027574',
    'author': 'Gerència Municipal',
    'author_email': None,

In [15]:
import requests
response = requests.get('https://opendata-ajuntament.barcelona.cat/data/api/action/current_package_list_with_resources')
dataset = response.json()

# Iterar sobre la lista de resultados y mostrar el título traducido (preferencia: es)
for item in dataset.get('result', []):
    title_translated = item.get('title_translated')
    id = item.get('id')
    if isinstance(title_translated, dict):
        titulo = title_translated.get('es')  
        print(f"id: {id},Título: {titulo}")
    else:
        # Fallback al campo 'title' si no existe 'title_translated'
        print(f"Título: {item.get('title', '')}")

id: 7e63eeb0-670a-4bcc-bee9-1d89697a4501,Título: Recibos y cuota del padrón de la Tasa de Vados del Ayuntamiento de Barcelona
id: e21b436f-7f84-4f7b-a3de-f7dc6b43264f,Título: Recibos y cuota del padrón del Impuesto de vehículos de tracción mecánica del Ayuntamiento de Barcelona
id: 778e5885-5bdb-416e-adbd-854632381ad1,Título: Personas inmigrantes
id: 3d317361-0be9-4178-8566-4ff0b33d65a3,Título: Personas emigrantes
id: 6b03a0f0-3900-4fe4-ada8-c9428e4751ed,Título: Bajas por inscripción indebida
id: 36599a99-ca8f-4ae6-8531-7fae51123e88,Título: Altas por omisión
id: bd19689e-0ebe-4a4b-a11e-eb519bac3453,Título: Defunciones
id: dde567a3-0c39-4216-a6b7-8588fdf4ef07,Título: Nacimientos
id: 28c20408-5bce-41db-9b83-1b85ac9b2548,Título: Población por región geográfica de nacionalidad y sexo
id: 9d03b5c9-d384-48f4-8a6e-e3e17f3ee04e,Título: Población por región geográfica de nacimiento y sexo

2. Dels resultats obtinguts, selecciona’n un que tingui recursos disponibles en CSV o JSON.

In [24]:
response=requests.get('https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show?id=28c20408-5bce-41db-9b83-1b85ac9b2548')
response.json()

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=package_show',
 'success': True,
 'result': {'notes_translated': {'ca': "Població de Barcelona agregada per la regió geogràfica associada a la nacionalitat i el sexe segons el registre del Padró Municipal d'Habitants a data 1 de gener de cada any",
   'en': 'Population of Barcelona aggregated by geographical region of nationality and sex according to the Municipal Register of Inhabitants on January 1 of each year',
   'es': 'Población de Barcelona agregada por región geográfica asociada a la nacionalidad y sexo según el registro del Padrón Municipal de Habitantes con fecha 1 de enero de cada año'},
  'geolocation': 'No',
  'code': 'pad_mdb_nacionalitat-regio_sexe',
  'url_tornada': {'ca': '', 'en': '', 'es': ''},
  'dataset_fields_description': 'Si la dada és menor que 5, s’indica com ‘’..’’',
  'fuente': "Ajuntament de Barcelona. Oficina Municipal de Dades (OMD). Padró Municipal d'Habitants",
  'private': False,
  'num_tags': 38,
  'api': 'Yes',
  'frequency': 'ANUAL',
  'id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
  'title_translated': {'ca': 'Població per regió geogràfica de nacionalitat i sexe',
   'en': 'Population by geographical region of nationality and sex',
   'es': 'Población por región geográfica de nacionalidad y sexo'},
  'metadata_modified': '2025-07-22T07:13:15.853137',
  'author': 'Gerència Municipal',
  'author_email': None,
  'isopen': True,
  'long_format': 'Yes',
  'state': 'active',
  'version': '',
  'mar_od': 'No',
  'relationships_as_object': [],
  'department': 'Oficina Municipal de Dades',
  'creator_user_id': '50d6b44b-a141-4dc6-b663-5deb4ab0dd63',
  'type': 'dataset',
  'resources': [{'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': True,
    'id': '3dce0dbd-5a7d-439a-b945-6bffc17a6c03',
    'size': '147685',
    'state': 'active',
    'api_access_number': 9,
    'api_access_number_absolute': 15,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 186,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2025_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-29T15:11:39.842927',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/3dce0dbd-5a7d-439a-b945-6bffc17a6c03/download',
    'downloads_absolute': 220,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:42.921796',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-30T02:10:53.332007',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 0,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '0dea1610-e615-4d81-9714-a374e1bb74c9',
    'size': '474533',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 71,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2025_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-29T15:10:20.024774',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/0dea1610-e615-4d81-9714-a374e1bb74c9/download',
    'downloads_absolute': 86,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:42.941971',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-30T02:10:53.355353',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 1,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '8caae93c-6196-490f-abd2-87eccda80776',
    'size': '146267',
    'state': 'active',
    'api_access_number': 1,
    'api_access_number_absolute': 1,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 61,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2024_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:17:19.851094',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/8caae93c-6196-490f-abd2-87eccda80776/download',
    'downloads_absolute': 72,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:42.962275',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.239828',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 2,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '08e3a0d7-7758-4d76-9e4b-89f2c2dc14c3',
    'size': '470187',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 27,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2024_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:15:57.855065',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/08e3a0d7-7758-4d76-9e4b-89f2c2dc14c3/download',
    'downloads_absolute': 34,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:42.983493',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.262492',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 3,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '7b7efabe-f08f-49e0-b1f9-eb116c6fdcc9',
    'size': '144228',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 31,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2023_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:14:35.491149',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/7b7efabe-f08f-49e0-b1f9-eb116c6fdcc9/download',
    'downloads_absolute': 35,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.003185',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.296396',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 4,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '026f6408-2fbe-404d-9620-6198bea2fd87',
    'size': '464252',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 16,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2023_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:13:13.699298',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/026f6408-2fbe-404d-9620-6198bea2fd87/download',
    'downloads_absolute': 19,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.026618',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.322010',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 5,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': 'a04fe536-d7ea-4fc5-95e5-ec029f58d265',
    'size': '143411',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 33,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:11:50.719551',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/a04fe536-d7ea-4fc5-95e5-ec029f58d265/download',
    'downloads_absolute': 36,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.058845',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.341514',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 6,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': 'ca281934-1f71-431c-a556-58382ca39be7',
    'size': '461353',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 13,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2022_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:10:28.721711',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/ca281934-1f71-431c-a556-58382ca39be7/download',
    'downloads_absolute': 15,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.071651',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.361323',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 7,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '8d695a37-9117-45de-af26-c58a91233421',
    'size': '143083',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 30,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2021_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:09:06.538321',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/8d695a37-9117-45de-af26-c58a91233421/download',
    'downloads_absolute': 33,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.089807',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.380763',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 8,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '65528d11-0a22-4f50-9b94-6f7f5e37ae65',
    'size': '460415',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 14,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2021_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:07:44.867534',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/65528d11-0a22-4f50-9b94-6f7f5e37ae65/download',
    'downloads_absolute': 16,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.116973',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.403562',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 9,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '3d849ad6-4208-4f90-b30c-8a1d7222dc30',
    'size': '142501',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 25,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2020_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:06:22.768197',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/3d849ad6-4208-4f90-b30c-8a1d7222dc30/download',
    'downloads_absolute': 27,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.138397',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.416970',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 10,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': 'fd0e65a4-c5d7-45fd-8117-bbbfefb92f33',
    'size': '458491',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'JSON',
    'downloads': 14,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2020_pad_mdb_nacionalitat-regio_sexe.json',
    'created': '2025-05-27T10:05:01.210643',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/fd0e65a4-c5d7-45fd-8117-bbbfefb92f33/download',
    'downloads_absolute': 16,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.164955',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'JSON',
     'created': '2025-05-28T02:10:58.437439',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "json" relates to format "JSON" and receives score: 3.'},
    'last_modified': None,
    'position': 11,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,
    'id': '94337cb7-3802-4eaf-87c4-be8c1d3c0fe4',
    'size': '141324',
    'state': 'active',
    'api_access_number': 0,
    'api_access_number_absolute': 0,
    'token_required': 'No',
    'hash': '',
    'description': '',
    'format': 'CSV',
    'downloads': 22,
    'mimetype_inner': None,
    'url_type': None,
    'token_provider': '',
    'hide_url': 'No',
    'mimetype': None,
    'cache_url': None,
    'name': '2019_pad_mdb_nacionalitat-regio_sexe.csv',
    'created': '2025-05-27T10:03:39.263480',
    'url': 'https://opendata-ajuntament.barcelona.cat/data/dataset/28c20408-5bce-41db-9b83-1b85ac9b2548/resource/94337cb7-3802-4eaf-87c4-be8c1d3c0fe4/download',
    'downloads_absolute': 25,
    'map_visualization_res': 'none',
    'qa': {'updated': '2025-11-10T02:11:43.184579',
     'openness_score': 3,
     'archival_timestamp': None,
     'format': 'CSV',
     'created': '2025-05-28T02:10:58.463042',
     'resource_timestamp': None,
     'openness_score_reason': 'This file had not been downloaded at the time of scoring it. URL extension "csv" relates to format "CSV" and receives score: 3.'},
    'last_modified': None,
    'position': 12,
    'revision_id': 'cd5fe50f-2c3d-4b61-9eb2-2c6cf11f1317',
    'resource_type': None},
   {'cache_last_updated': None,
    'token_type': '',
    'package_id': '28c20408-5bce-41db-9b83-1b85ac9b2548',
    'datastore_active': False,

3. Amb el resource_id del recurs seleccionat, realitza una consulta mitjançant datastore_search per:

Recuperar almenys 100 registres.

In [53]:
import requests

# URL base
url_base = 'https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search'

# Parámetros de consulta
parametros = {
    'resource_id': '3dce0dbd-5a7d-439a-b945-6bffc17a6c03',
    'limit': 100
}

# Realizar el GET request con el diccionario de parámetros
response = requests.get(url_base, params=parametros)
data=response.json()
data

{'help': 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/help_show?name=datastore_search',
 'success': True,
 'result': {'resource_id': '3dce0dbd-5a7d-439a-b945-6bffc17a6c03',
  'fields': [{'type': 'int4', 'id': '_id'},
   {'type': 'timestamp', 'id': 'Data_Referencia'},
   {'type': 'numeric', 'id': 'Codi_Districte'},
   {'type': 'text', 'id': 'Nom_Districte'},
   {'type': 'numeric', 'id': 'Codi_Barri'},
   {'type': 'text', 'id': 'Nom_Barri'},
   {'type': 'text', 'id': 'Valor'},
   {'type': 'numeric', 'id': 'NACIONALITAT_REGIO'},
   {'type': 'numeric', 'id': 'SEXE'}],
  'records': [{'NACIONALITAT_REGIO': '1',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '20',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 1},
   {'NACIONALITAT_REGIO': '1',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '31',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 2},
   {'NACIONALITAT_REGIO': '2',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '12',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 3},
   {'NACIONALITAT_REGIO': '2',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '15',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 4},
   {'NACIONALITAT_REGIO': '3',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '695',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 5},
   {'NACIONALITAT_REGIO': '3',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '1703',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 6},
   {'NACIONALITAT_REGIO': '4',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '7',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 7},
   {'NACIONALITAT_REGIO': '4',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '8',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 8},
   {'NACIONALITAT_REGIO': '5',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '72',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 9},
   {'NACIONALITAT_REGIO': '5',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '173',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 10},
   {'NACIONALITAT_REGIO': '6',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '147',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 11},
   {'NACIONALITAT_REGIO': '6',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '176',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 12},
   {'NACIONALITAT_REGIO': '7',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '263',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 13},
   {'NACIONALITAT_REGIO': '7',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '264',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 14},
   {'NACIONALITAT_REGIO': '8',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '1743',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 15},
   {'NACIONALITAT_REGIO': '8',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '1745',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 16},
   {'NACIONALITAT_REGIO': '9',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '201',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 17},
   {'NACIONALITAT_REGIO': '9',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '235',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 18},
   {'NACIONALITAT_REGIO': '10',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '18',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 19},
   {'NACIONALITAT_REGIO': '10',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '15',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 20},
   {'NACIONALITAT_REGIO': '11',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '266',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 21},
   {'NACIONALITAT_REGIO': '11',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '208',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 22},
   {'NACIONALITAT_REGIO': '12',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '2740',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 23},
   {'NACIONALITAT_REGIO': '12',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '5028',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 24},
   {'NACIONALITAT_REGIO': '13',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '2224',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 25},
   {'NACIONALITAT_REGIO': '13',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '1677',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 26},
   {'NACIONALITAT_REGIO': '14',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '184',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 27},
   {'NACIONALITAT_REGIO': '14',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '240',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 28},
   {'NACIONALITAT_REGIO': '15',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '702',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 29},
   {'NACIONALITAT_REGIO': '15',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '493',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 30},
   {'NACIONALITAT_REGIO': '16',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '431',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 31},
   {'NACIONALITAT_REGIO': '16',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '488',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 32},
   {'NACIONALITAT_REGIO': '17',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '12728',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 33},
   {'NACIONALITAT_REGIO': '17',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '13133',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 34},
   {'NACIONALITAT_REGIO': '18',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '853',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 35},
   {'NACIONALITAT_REGIO': '18',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '918',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 36},
   {'NACIONALITAT_REGIO': '19',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '21',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 37},
   {'NACIONALITAT_REGIO': '19',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '22',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 38},
   {'NACIONALITAT_REGIO': '23',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '12',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 39},
   {'NACIONALITAT_REGIO': '23',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '1',
    'Nom_Barri': 'el Raval',
    'Valor': '6',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 40},
   {'NACIONALITAT_REGIO': '1',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '8',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 41},
   {'NACIONALITAT_REGIO': '1',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '15',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 42},
   {'NACIONALITAT_REGIO': '2',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '8',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 43},
   {'NACIONALITAT_REGIO': '2',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '9',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 44},
   {'NACIONALITAT_REGIO': '3',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '419',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 45},
   {'NACIONALITAT_REGIO': '3',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '1654',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 46},
   {'NACIONALITAT_REGIO': '4',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '5',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 47},
   {'NACIONALITAT_REGIO': '4',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '9',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 48},
   {'NACIONALITAT_REGIO': '5',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '36',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 49},
   {'NACIONALITAT_REGIO': '5',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '252',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 50},
   {'NACIONALITAT_REGIO': '6',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '51',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 51},
   {'NACIONALITAT_REGIO': '6',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '79',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 52},
   {'NACIONALITAT_REGIO': '7',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '277',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 53},
   {'NACIONALITAT_REGIO': '7',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '184',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 54},
   {'NACIONALITAT_REGIO': '8',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '1223',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 55},
   {'NACIONALITAT_REGIO': '8',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '1226',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 56},
   {'NACIONALITAT_REGIO': '9',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '213',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 57},
   {'NACIONALITAT_REGIO': '9',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '183',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 58},
   {'NACIONALITAT_REGIO': '10',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '15',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 59},
   {'NACIONALITAT_REGIO': '10',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '10',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 60},
   {'NACIONALITAT_REGIO': '11',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '89',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 61},
   {'NACIONALITAT_REGIO': '11',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '71',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 62},
   {'NACIONALITAT_REGIO': '12',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '661',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 63},
   {'NACIONALITAT_REGIO': '12',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '7089',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 64},
   {'NACIONALITAT_REGIO': '13',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '223',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 65},
   {'NACIONALITAT_REGIO': '13',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '151',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 66},
   {'NACIONALITAT_REGIO': '14',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '144',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 67},
   {'NACIONALITAT_REGIO': '14',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '155',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 68},
   {'NACIONALITAT_REGIO': '15',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '462',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 69},
   {'NACIONALITAT_REGIO': '15',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '368',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 70},
   {'NACIONALITAT_REGIO': '16',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '364',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 71},
   {'NACIONALITAT_REGIO': '16',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '403',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 72},
   {'NACIONALITAT_REGIO': '17',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '5091',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 73},
   {'NACIONALITAT_REGIO': '17',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '5392',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 74},
   {'NACIONALITAT_REGIO': '18',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '637',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 75},
   {'NACIONALITAT_REGIO': '18',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '631',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 76},
   {'NACIONALITAT_REGIO': '19',
    'Codi_Districte': '1',
    'SEXE': '1',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '31',
    'Data_Referencia': '2025-01-01T00:00:00',
    '_id': 77},
   {'NACIONALITAT_REGIO': '19',
    'Codi_Districte': '1',
    'SEXE': '2',
    'Nom_Districte': 'Ciutat Vella',
    'Codi_Barri': '2',
    'Nom_Barri': 'el Barri Gòtic',
    'Valor': '32',

4. Converteix els resultats a un DataFrame.

In [55]:
import pandas as pd


# URL base
url_base = 'https://opendata-ajuntament.barcelona.cat/data/api/action/datastore_search'

# Parámetros de consulta
parametros = {
    'resource_id': '3dce0dbd-5a7d-439a-b945-6bffc17a6c03',
    'limit': 100
}

# 1. Realizar el GET request
response = requests.get(url_base, params=parametros)
response.raise_for_status() # Buena práctica para lanzar una excepción si el request falla

# 2. Convertir la respuesta a JSON
data = response.json()

# 3. Extraer la lista de registros ('records')
# Los datos tabulares de CKAN suelen estar en data['result']['records']
try:
    registros = data['result']['records']
except KeyError:
    print("Error: No se encontró la clave 'result' o 'records' en la respuesta de la API.")
    registros = [] # Inicializa como lista vacía en caso de error

# 4. Crear el DataFrame
df = pd.DataFrame(registros)

# Mostrar las primeras filas del DataFrame (opcional)
df.head()

,NACIONALITAT_REGIO,Codi_Districte,SEXE,Nom_Districte,Codi_Barri,Nom_Barri,Valor,Data_Referencia,_id
0,1,1,1,Ciutat Vella,1,el Raval,20,2025-01-01T00:00:00,1
1,1,1,2,Ciutat Vella,1,el Raval,31,2025-01-01T00:00:00,2
2,2,1,1,Ciutat Vella,1,el Raval,12,2025-01-01T00:00:00,3
3,2,1,2,Ciutat Vella,1,el Raval,15,2025-01-01T00:00:00,4
4,3,1,1,Ciutat Vella,1,el Raval,695,2025-01-01T00:00:00,5

5. Desa el DataFrame en un fitxer .csv.

In [ ]:
df.to_csv('Población_nac_sexo.csv')