Nivell 1

1.
Importa com un DataFrame l'arxiu sprint10.xlsx. Assegura't que el fitxer s'importa correctament, amb els noms de columnes que li corresponen, sense manipular l'arxiu original.

Ordena el DataFrame pel país d'origen. En cas d'empat, ordena pel nom de la ciutat.

Mostra les primeres 10 files.

Addicionalment, fes un print on comprovi que el DNI només té valors únics.

In [2]:
#Importar el archivo de excel utilizando la función read_excel de la libreria Pandas
import pandas as pd
df = pd.read_excel(r"C:\Users\jprom\Desktop\IT Academy\Python\Data Analytics\Sprint 10\sprint10.xlsx")
df_1 = df.copy()
df_1

,Dades de l'enquesta de treballadors 2025,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
3,0,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,True,Grup A
4,1,Lea,Schneider,79911049R,Alemanya,Munic,22,9,1950,D,2.668 €,True,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,995,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,True,NaN,Grup A
999,996,Sophie,Taylor Smith,50261072D,Regne Unit,Londres,26,12,2005,D,1.663 €,NaN,True,Grup B
1000,997,Sophie,Brown,74953524F,Regne Unit,Londres,17,5,1983,D,2.189 €,True,NaN,Grup C
1001,998,Isla,Taylor Smith,67837921D,Regne Unit,Londres,7,5,1965,D,1.237 €,NaN,True,Grup A
1002,999,William,Taylor,14371347B,Regne Unit,Londres,11,10,1957,H,1.017 €,NaN,True,Grup A

In [3]:
#Mediante el método loc[] se nombran las columnas del DF, creando una lista llamada nombre_columnas  
nombre_columnas = df_1.loc[2]
df_1.columns = list(nombre_columnas)
df_1

,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Generades aleatòriament per seguretat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
3,0,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,True,Grup A
4,1,Lea,Schneider,79911049R,Alemanya,Munic,22,9,1950,D,2.668 €,True,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,995,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,True,NaN,Grup A
999,996,Sophie,Taylor Smith,50261072D,Regne Unit,Londres,26,12,2005,D,1.663 €,NaN,True,Grup B
1000,997,Sophie,Brown,74953524F,Regne Unit,Londres,17,5,1983,D,2.189 €,True,NaN,Grup C
1001,998,Isla,Taylor Smith,67837921D,Regne Unit,Londres,7,5,1965,D,1.237 €,NaN,True,Grup A
1002,999,William,Taylor,14371347B,Regne Unit,Londres,11,10,1957,H,1.017 €,NaN,True,Grup A

In [4]:
#Se eliminan las dos primeras filas con valores nulos del DF y la fila que contiene los nombres de las columnas
df_employees = df_1.drop([0,1,2])
df_employees

,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
3,0,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,True,Grup A
4,1,Lea,Schneider,79911049R,Alemanya,Munic,22,9,1950,D,2.668 €,True,NaN,Grup D
5,2,Anna,Müller,23128433S,Alemanya,Munic,18,3,1956,D,1.280 €,NaN,True,Grup A
6,3,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,True,NaN,Grup B
7,4,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,True,Grup B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
998,995,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1.405 €,True,NaN,Grup A
999,996,Sophie,Taylor Smith,50261072D,Regne Unit,Londres,26,12,2005,D,1.663 €,NaN,True,Grup B
1000,997,Sophie,Brown,74953524F,Regne Unit,Londres,17,5,1983,D,2.189 €,True,NaN,Grup C
1001,998,Isla,Taylor Smith,67837921D,Regne Unit,Londres,7,5,1965,D,1.237 €,NaN,True,Grup A
1002,999,William,Taylor,14371347B,Regne Unit,Londres,11,10,1957,H,1.017 €,NaN,True,Grup A

In [5]:
#Renombrar el DF y realizamos la ordenación, mediante la función sort_values() por valores de las columnas País de Origen y Ciudad de forma ascendente
df_employees_ordenado = df_employees.sort_values(["País d'origen", "Ciutat"], ascending=True)
#Mostrar las 10 primeras filas con el método head()
df_employees_ordenado.head(10)

,NaN,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
3,0,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951 €,NaN,True,Grup A
6,3,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1.769 €,True,NaN,Grup B
7,4,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2.013 €,NaN,True,Grup B
8,5,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1.557 €,True,NaN,Grup B
19,16,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2.754 €,True,NaN,Grup D
23,20,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1.370 €,True,NaN,Grup A
9,6,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1.314 €,NaN,True,Grup A
12,9,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2.464 €,NaN,True,Grup C
15,12,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2.035 €,True,NaN,Grup C
16,13,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2.042 €,NaN,True,Grup B

In [6]:
#Comprobamos si la columna 'DNI' del DF tiene valores únicos o no
unicos_DNI = df_employees_ordenado['DNI'].nunique()

if unicos_DNI == len(df_employees_ordenado['DNI']):
    print("'DNI tiene todos los valores únicos")
else:
    print("'DNI' NO tiene todos los valores únicos")

'DNI tiene todos los valores únicos

---------------------------------------------------------------------------------------------------------------------

2.
Crea una columna que sigui el nom complet.

Crea una columna si la persona és nascuda a Espanya o no.

Posa el DNI com a índex del DataFrame (noms de files).

Substitueix el nom de les columnes Dia de Naixement, Mes de Naixement i Any de Naixement per Dia, Mes i Any.

Substitueix H per Home, D per Dona, A per Altres i NC per una dada faltant (nan/null/na).

Mostra tots els canvis que has realitzat en una sola taula.

In [ ]:
# Crear una nueva columna 'Nombre_Completo' mediante concatenado de las existentes= 'Nom' y 'Cognoms'
df_employees_ordenado['Nombre_Completo'] = df_employees_ordenado['Nom'] + ' ' + df_employees_ordenado['Cognoms']

# Crear una nueva columna para los nacidos/as en España
df_employees_ordenado['Español/a'] = df_employees_ordenado["País d'origen"] == 'Espanya'

# Colocar el DNI como índice del DataFrame
df_employees_ordenado.set_index('DNI', inplace=True)
df_employees_ordenado.index

Index(['28973553Z', '37399141L', '37368317L', '21390098Z', '44060014R',
       '14773153R', '23266650S', '83274277X', '60161784X', '60982309S',
       ...
       '74953524F', '67837921D', '14371347B', '37846341L', '86350703G',
       '89577876S', '57441590Y', '58204038A', '28367234K', '82046699J'],
      dtype='object', name='DNI', length=1000)

In [33]:
#Substituir el nombre de las columnas por Dia, Mes y Any
df_idx_DNI = df_employees_ordenado.rename(columns={'Dia de Naixement': 'Dia', 'Mes de Naixement' : 'Mes', 'Any de Naixement' : 'Any'})

#Sustituir el nombre de los valores por Home, Dona, Altres, NC
df_idx_DNI['Gènere'] = df_idx_DNI['Gènere'].replace({'H':'Home', 'D':'Dona', 'A': 'Altres'})

#Mostrar todos los cambios realizado en una sola tabla
df_idx_DNI.head()

,NaN,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Español/a
DNI,,,,,,,,,,,,,,,
28973553Z,0,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,NaN,True,Grup A,Mia Schneider Fischer,False
37399141L,3,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,True,NaN,Grup B,Laura Schneider Fischer,False
37368317L,4,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,NaN,True,Grup B,Lea Schneider Schneider,False
21390098Z,5,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,True,NaN,Grup B,Mia Fischer,False
44060014R,16,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,True,NaN,Grup D,Jonas Schneider,False

---------------------------------------------------------------------------------------------------------------------

3.
Junta les columnes Fills i No Fills en una sola columna, utilitzant el mètode .apply() i definint una funció que resolgui el problema. La columna nova ha de dir-se "Fills" i prendre els valors "Sí" o "No".

In [9]:
#Crear una función que asigne según una condición un valor a la columna "Fills"
def crear_fills(row):
    # Si la columna 'Fills' tiene valor True, retorna 'Sí'
    if row['Fills'] == True:
        return 'Sí'
    # Si la columna 'No Fills' tiene valor True, retorna 'No'
    elif row['No Fills'] == True:
        return 'No'
    # Si ambas son NaN, retorna NaN
    else:
        return pd.NA

# Aplica la función mediante el método apply (), para crear la nueva columna 'Fills'
df_idx_DNI['Fills'] = df_idx_DNI.apply(crear_fills, axis=1)
df_idx_DNI

,NaN,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Español/a
DNI,,,,,,,,,,,,,,,
28973553Z,0,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,True,Grup A,Mia Schneider Fischer,False
37399141L,3,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,NaN,Grup B,Laura Schneider Fischer,False
37368317L,4,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,True,Grup B,Lea Schneider Schneider,False
21390098Z,5,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,NaN,Grup B,Mia Fischer,False
44060014R,16,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,NaN,Grup D,Jonas Schneider,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,987,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,No,True,Grup B,Emily Taylor Jones,False
57441590Y,991,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Sí,NaN,Grup A,George Brown Jones,False
58204038A,992,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,No,True,Grup A,Olivia Brown Brown,False
28367234K,994,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,No,True,Grup A,Isla Jones Brown,False
82046699J,995,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Sí,NaN,Grup A,William Smith,False

---------------------------------------------------------------------------------------------------------------------

4.
Crea una taula resum que permeti veure el sou mig, medià, mínim i màxim per Gènere.

Ordena la taula en funció del sou mig.

In [35]:
# Convertir "Salari mensual" a valor numérico (remover "€", reemplazar "," con ".", y strip espacios)
df_idx_DNI['Salari mensual numeric'] = (
	df_idx_DNI['Salari mensual']
    .str.replace('€', '', regex=False)
	.str.replace('.', '', regex=False)
	.str.replace(',', '.', regex=False)
	.str.strip()
	.astype (float)
)

# Agrupar por "Gènere" y calcular el salario (mean, median, min, max) en una nueva tabla
df_resum = (df_idx_DNI.groupby("Gènere")["Salari mensual numeric"]
            .agg(['mean', 'median', 'min', 'max'])
            .sort_values("mean", ascending=False)
           )
df_resum

               mean  median    min     max
Gènere
Home    1643.249443  1531.0  737.0  3356.0
Altres  1626.588235  1545.0  703.0  3175.0
NC      1568.866667  1443.0  758.0  2969.0
Dona    1469.443182  1361.5  665.0  3021.0

---------------------------------------------------------------------------------------------------------------------

5.
Crea una taula resum amb el salari mig per gènere (files) i país d'origen (columnes).

Afegeix-hi les mitjanes als marges de la taula.

(EXTRA): Aplica format condicional a la taula per veure en un color més intens els valors més elevats

In [ ]:
#Mediante la función crosstab, creamos una tabla tabulada por Género (filas) y País de Origen (columnas)
df_crosstab = pd.crosstab(
    df_idx_DNI["Gènere"],
    df_idx_DNI["País d'origen"],
    df_idx_DNI["Salari mensual numeric"],
    aggfunc='mean',
    margins=True,
    margins_name="Mitjana"
)

# df_crosstab             
#Aplicar formato condicional mediante la propiedad style para ver los valores máximos por columna
df_crosstab.style.apply(lambda x:['color: red; background-color: yellow' if v == x.max() else '' for v in x])

In [12]:
# Tabla resumen: salario medio por 'gènere' (filas) y 'país d'origen' (columnas)
df_pivot = pd.pivot_table(
	df_idx_DNI,
	values="Salari mensual numeric",
	index="Gènere",
	columns="País d'origen",
	aggfunc="mean",
	margins=True,
	margins_name="Mitjana"
)

def color_max(valor):
        if valor > 1500:
            return 'color: red; background-color: yellow' #color rojo para texto, amarillo para fondo
    
df_pivot.style.map(color_max)

---------------------------------------------------------------------------------------------------------------------

6.
Crea una columna nova que sigui la data de naixament en format Datetime a partir de les columnes dia, mes i any. Utilitzant aquesta columna crea una funció que donada una data, et calculi l'edat actual a dia d'avui.

Utilitza la funció que acabes de crear per generar una columna nova al DataFrame amb l'edat actual.

In [13]:
#Validar que el formato de fecha sea un string
"""
df_idx_DNI['Dia']=df_idx_DNI['Dia'].astype(str)
df_idx_DNI['Mes']=df_idx_DNI['Mes'].astype(str)
df_idx_DNI['Any'] = df_idx_DNI['Any'].astype(str)
"""
#Creamos una columna nueva con el formato DateTime y renombramos cada etiqueta de columna a los valores del formato
df_idx_DNI['Date_Time'] = pd.to_datetime(
	df_idx_DNI[['Any', 'Mes', 'Dia']].rename(columns={'Any': 'year', 'Mes': 'month', 'Dia': 'day'})
    )

#Creamos una función a partir del módulo datetime que tomando una fecha como arg, y la variabla de fecha actual (datetime), retorne la edad
from datetime import datetime
def calcular_edad(fecha):
    #La fecha está en formato TimeStamp por lo que lo usamos directamente
    fecha_nac = fecha
    fecha_actual = datetime.now()
    edad = fecha_actual.year - fecha_nac.year
    #Si la fecha actual es anterior al mes/día de nacimiento, resta un año
    if (fecha_actual.month, fecha_actual.day) < (fecha_nac.month, fecha_nac.day):
        edad -= 1
    return edad

df_idx_DNI['Edad_actual'] = df_idx_DNI['Date_Time'].apply(calcular_edad)

df_idx_DNI

,NaN,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Español/a,Salari mensual numeric,Date_Time,Edad_actual
DNI,,,,,,,,,,,,,,,,,,
28973553Z,0,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,True,Grup A,Mia Schneider Fischer,False,951.0,1976-10-22,48
37399141L,3,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,NaN,Grup B,Laura Schneider Fischer,False,1769.0,1958-02-02,67
37368317L,4,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,True,Grup B,Lea Schneider Schneider,False,2013.0,2005-10-23,19
21390098Z,5,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,NaN,Grup B,Mia Fischer,False,1557.0,1950-08-11,75
44060014R,16,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,NaN,Grup D,Jonas Schneider,False,2754.0,1985-11-22,39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,987,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,No,True,Grup B,Emily Taylor Jones,False,2033.0,1958-03-28,67
57441590Y,991,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Sí,NaN,Grup A,George Brown Jones,False,1130.0,1979-12-27,45
58204038A,992,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,No,True,Grup A,Olivia Brown Brown,False,1023.0,1952-08-28,73
28367234K,994,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,No,True,Grup A,Isla Jones Brown,False,1197.0,1999-03-28,26
82046699J,995,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Sí,NaN,Grup A,William Smith,False,1405.0,1997-05-19,28

---------------------------------------------------------------------------------------------------------------------

Nivell 2

1.
Utilitzant el següent DataFrame, adjunta la columna "Increment" al dataframe del nivell anterior.

Actualitza la columna salari en funció dels percentatges que s'adjunten. No modifiquis manualment els increments, escriu codi Python per fer les conversions necessàries.

In [14]:
#Crear el DF 'Increment' 
import pandas as pd

df_increment = pd.DataFrame({"Grup":["Grup A","Grup B","Grup C", "Grup D" ] , "Increment":

["5%","3,5%","2%","8%"]})

df_increment

     Grup Increment
0  Grup A        5%
1  Grup B      3,5%
2  Grup C        2%
3  Grup D        8%

In [15]:
# Añadir la columna 'Increment' al DataFrame principal según el 'Grup', mediante la función merge() y eliminamos la columna 'Grup'"Sprint 10.ipynb"
#del DF 'Increment'
df_idx_DNI = df_idx_DNI.merge(
    df_increment[['Grup', 'Increment']],
    left_on='Grup Professional',
    right_on='Grup',
    how='left'
).drop(columns=['Grup'])
df_idx_DNI

,NaN,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Español/a,Salari mensual numeric,Date_Time,Edad_actual,Increment
0,0,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,True,Grup A,Mia Schneider Fischer,False,951.0,1976-10-22,48,5%
1,3,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,NaN,Grup B,Laura Schneider Fischer,False,1769.0,1958-02-02,67,"3,5%"
2,4,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,True,Grup B,Lea Schneider Schneider,False,2013.0,2005-10-23,19,"3,5%"
3,5,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,NaN,Grup B,Mia Fischer,False,1557.0,1950-08-11,75,"3,5%"
4,16,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,NaN,Grup D,Jonas Schneider,False,2754.0,1985-11-22,39,8%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,987,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,No,True,Grup B,Emily Taylor Jones,False,2033.0,1958-03-28,67,"3,5%"
996,991,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Sí,NaN,Grup A,George Brown Jones,False,1130.0,1979-12-27,45,5%
997,992,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,No,True,Grup A,Olivia Brown Brown,False,1023.0,1952-08-28,73,5%
998,994,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,No,True,Grup A,Isla Jones Brown,False,1197.0,1999-03-28,26,5%
999,995,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Sí,NaN,Grup A,William Smith,False,1405.0,1997-05-19,28,5%

In [16]:
# Convertir los valores de la columna 'Increment' a float
# Eliminar el signo '%' y reemplazar ',' por '.'
df_idx_DNI['Increment'] = (
	df_idx_DNI['Increment']
	.str.replace('%', '', regex=False)
	.str.replace(',', '.', regex=False)
	.astype(float)
)

# Calcular el salario actualizado usando el incremento como porcentaje
df_idx_DNI["Salari_mensual_actualizat"] = (
	df_idx_DNI["Salari mensual numeric"] * (1 + df_idx_DNI["Increment"] / 100)
)
df_idx_DNI

,NaN,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Any,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_Completo,Español/a,Salari mensual numeric,Date_Time,Edad_actual,Increment,Salari_mensual_actualizat
0,0,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Altres,951 €,No,True,Grup A,Mia Schneider Fischer,False,951.0,1976-10-22,48,5.0,998.550
1,3,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Dona,1.769 €,Sí,NaN,Grup B,Laura Schneider Fischer,False,1769.0,1958-02-02,67,3.5,1830.915
2,4,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Dona,2.013 €,No,True,Grup B,Lea Schneider Schneider,False,2013.0,2005-10-23,19,3.5,2083.455
3,5,Mia,Fischer,Alemanya,Berlín,11,8,1950,Dona,1.557 €,Sí,NaN,Grup B,Mia Fischer,False,1557.0,1950-08-11,75,3.5,1611.495
4,16,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Home,2.754 €,Sí,NaN,Grup D,Jonas Schneider,False,2754.0,1985-11-22,39,8.0,2974.320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,987,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Dona,2.033 €,No,True,Grup B,Emily Taylor Jones,False,2033.0,1958-03-28,67,3.5,2104.155
996,991,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Home,1.130 €,Sí,NaN,Grup A,George Brown Jones,False,1130.0,1979-12-27,45,5.0,1186.500
997,992,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Altres,1.023 €,No,True,Grup A,Olivia Brown Brown,False,1023.0,1952-08-28,73,5.0,1074.150
998,994,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Dona,1.197 €,No,True,Grup A,Isla Jones Brown,False,1197.0,1999-03-28,26,5.0,1256.850
999,995,William,Smith,Regne Unit,Manchester,19,5,1997,Home,1.405 €,Sí,NaN,Grup A,William Smith,False,1405.0,1997-05-19,28,5.0,1475.250

2.
Utilitzant un bucle, exporta en 4 fitxers (format .xlsx o .csv) les dades de cada Grup Professional.

Per exemple: "dades_GrupA.xlsx" , "dades_GrupB.xlsx" ...

Exporta un 5è DataFrame en format .xlsx o .csv que contingui quants treballadors hi ha per cada Grup Professional, quin és el seu sou mig i quina és la seva edat mediana.

In [17]:
# Iterar sobre los cuatro grupos, filtrar y exportar
grupos = ['Grup A', 'Grup B', 'Grup C', 'Grup D']

#Mediante un bucle for iteramos a partir de la variable grupos, en el DF filtrado por grupo
for grupo in grupos:
    df_filtrado = df_idx_DNI[df_idx_DNI["Grup Professional"] == grupo]
    #Asignar un nombre de archivo a la salida
    nombre_archivo = f"dades_{grupo.replace(' ', '')}.xlsx"
    #Exportar a excel el df filtrado por grupos, eliminando el index
    df_filtrado.to_excel(nombre_archivo, index=False)
    print(f"Exportado: {nombre_archivo}")

Exportado: dades_GrupA.xlsx
Exportado: dades_GrupB.xlsx
Exportado: dades_GrupC.xlsx
Exportado: dades_GrupD.xlsx

In [18]:
#Exportar un quinto DF con las condiciones solicitadas
df_5 = (df_idx_DNI.groupby("Grup Professional")[['Nombre_Completo','Salari mensual numeric', 'Edad_actual']]
        .agg({'Nombre_Completo': 'count', 'Salari mensual numeric':'mean','Edad_actual':'median'})
)
df_renombrado = df_5.rename(columns={'Nombre_Completo':'Quantitat_treballadors', 'Salari mensual numeric':'Sou_mig', 'Edad_actual': 'Edad_mediana'})

#Exportar el DF a excel 
df_renombrado.to_excel('dades_Grups.xlsx')
df_renombrado

                   Quantitat_treballadors      Sou_mig  Edad_mediana
Grup Professional
Grup A                                490  1155.546939          50.0
Grup B                                318  1666.232704          47.0
Grup C                                137  2244.306569          51.0
Grup D                                 55  2871.127273          43.0

---------------------------------------------------------------------------------------------------------------------

Nivell 3

1.
Crea una funció que prengui un dataframe com a paràmetre d'entrada.

La funció ha de crear (i exportar) un gràfic automàticament per a cada columna del dataframe. 

Per exemple:
un histograma/boxplot si la variable és numèrica
unes barres dels valors més freqüents si és categòrica
unes barres dels anys més freqüents si la dada està en format data.
La idea és crear una funció que funcioni per qualsevol dataframe, no només amb el que hem treballat fins ara.

Mostra el resultat de la funció en algun dels datasets d’exemple que conté el paquet seaborn. Per exemple, iris, penguins o titanic.

In [19]:
#Mediante la librería seaborn, importamos el DF 'penguins'
import seaborn as sns
df = sns.load_dataset('penguins')
df

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [20]:
#Importar las librerías 'numpy' y 'matplotlib' para realizar las gráficas solicitadas
import numpy as np
import matplotlib.pyplot as plt

#Crear una función que clasifica las columnas del DataFrame y genera un gráfico apropiado para cada una según el topo de variable
# Numérica, Categórica, Fecha (Histograma, Barras de Frecuencia o Barras de Años).
#Args: El DataFrame de pandas a analizar y graficar.
def clasificar_y_graficar_variables(df: pd.DataFrame):
    
    # Identificar columnas numéricas
    columnas_num = df.select_dtypes(include=np.number).columns.tolist()
    
    # Identificar columnas de fecha/hora (datetime)
    # Usamos 'datetime64' para capturar todos los subtipos de fecha de NumPy/Pandas
    columnas_fecha = df.select_dtypes(include=['datetime', 'datetime64']).columns.tolist()

    # Inicializar el diccionario de resultados
    clasificacion = {
        'numericas': columnas_num,
        'fechas': columnas_fecha,
        # Si no es numérica ni fecha, se clasifica como categórica (object, bool, category, etc.)
        'categoricas': [col for col in df.columns if col not in columnas_num and col not in columnas_fecha]
    }
    #Imprimimos las varias clasificadas según tipo de dato
    print(clasificacion)
    
    
    # Gráficos para Columnas Numéricas (Histograma)
    # Bucle for para iterar sobre todas las columnas y clasificar los gráficos por tipo de dato numérico
    for col in clasificacion['numericas']:
        plt.figure(figsize=(12, 5))
        df[col].plot(kind='hist', bins=15, edgecolor='black', color='skyblue')
        plt.title(f'Histograma de Frecuencia de {col}', fontsize=12)
        plt.xlabel(col)
        plt.ylabel('Frecuencia')
    
        
        nombre_archivo_imagen = f"grafico_numerica_{col}.png"
        plt.savefig(nombre_archivo_imagen)
        plt.close()
        print(f"Gráfico guardado: {nombre_archivo_imagen}")


    # Gráficos para Columnas Categóricas (Barras de Frecuencia)
    for col in clasificacion['categoricas']:
        plt.figure(figsize=(8, 6))
        # Contar la frecuencia de los valores y graficar las barras
        conteo = df[col].value_counts().head(10) # Mostrar los 10 más frecuentes
        conteo.plot(kind='bar', color='green', alpha=0.7)
        
        plt.title(f'Frecuencia de las Categorías en {col}', fontsize=12)
        plt.xlabel(col)
        plt.ylabel('Conteo')
        plt.xticks(rotation=45, ha='right') # Rotar etiquetas para mejor lectura
        plt.tight_layout()
        
        nombre_archivo_imagen = f"grafico_categorica_{col}.png"
        plt.savefig(nombre_archivo_imagen)
        plt.close()
        print(f"Gráfico guardado: {nombre_archivo_imagen}")


    # Gráficos para Columnas de Fecha/Hora (Barras de Frecuencia por Año)
    for col in clasificacion['fechas']:
        plt.figure(figsize=(8, 6))
        # Extraer el año y contar su frecuencia
        conteo_anual = df[col].dt.year.value_counts().sort_index()
        conteo_anual.plot(kind='bar', color='purple', alpha=0.7)
        
        plt.title(f'Frecuencia Anual de {col}', fontsize=12)
        plt.xlabel('Año')
        plt.ylabel('Conteo de Registros')
        plt.xticks(rotation=0)
        plt.tight_layout()
        
        nombre_archivo_imagen = f"grafico_fecha_{col}.png"
        plt.savefig(nombre_archivo_imagen)
        plt.close()
        print(f"Gráfico guardado: {nombre_archivo_imagen}")
    
graficos = clasificar_y_graficar_variables(df)

{'numericas': ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g'], 'fechas': [], 'categoricas': ['species', 'island', 'sex']}
Gráfico guardado: grafico_numerica_bill_length_mm.png
Gráfico guardado: grafico_numerica_bill_depth_mm.png
Gráfico guardado: grafico_numerica_flipper_length_mm.png
Gráfico guardado: grafico_numerica_body_mass_g.png
Gráfico guardado: grafico_categorica_species.png
Gráfico guardado: grafico_categorica_island.png
Gráfico guardado: grafico_categorica_sex.png

2.
Carrega l'arxiu matriu_distancies.xlsx a pandas, de manera que els noms de files i els noms de columnes siguin els de les ciutats. Borra "Las Palmas de Gran Canaria" i "Palma" perquè poguem fer el trajecte en cotxe.

Ens interessa visitar totes les ciutats principals d'Espanya recorrent la mínima distància possible.

No cal que ho facis de forma òptima, ens interessa que desenvolupis una solució raonable utilitzant les eines que tens actualment.

Per exemple, una aproximació senzilla (que no òptima) seria anant sempre a la ciutat més propera que no haguem visitat encara

Fes una funció que donada la matriu de distàncies i la ciutat d'origen, faci una proposta de ruta que sigui el més curta possible que puguis, retornant una llista amb l'ordre de visita. Dóna també la distància total recorreguda.

(EXTRA) Des de quina ciutat la ruta seria més curta amb l'algoritme plantejat

In [21]:
#Cargar el archivo matriz con las distancias entre ciudades
import pandas as pd
df = pd.read_excel(r"C:\Users\jprom\Desktop\IT Academy\Python\Data Analytics\Sprint 10\matriu_distancies.xlsx")
df_distancies = df.copy()

#Eliminar las columnas y filas de las ciudades : Palma', 'Las Palmas de Gran Canaria'.
df_distancies = df.drop(['Palma', 'Las Palmas de Gran Canaria'], axis=1, inplace=True)
df_distancies = df.drop([6,7])

#Renombrar la columna 'Unnamed' y luego asignar esta como índice del DF
df_distancies_idx = df_distancies.rename(columns={'Unnamed: 0': 'Ciudades'})
df_distancies_idx.set_index('Ciudades', inplace=True)
df_distancies_idx

,Barcelona,Valencia,Sevilla,Zaragoza,Málaga,Murcia,Bilbao,Alicante,Córdoba,Valladolid,Vigo,Gijón,Hospitalet de Llobregat
Ciudades,,,,,,,,,,,,,
Barcelona,NaN,303.0,831.0,256.0,770.0,471.0,469.0,407.0,711.0,576.0,908.0,686.0,7.0
Valencia,303.0,NaN,541.0,246.0,468.0,177.0,473.0,125.0,421.0,441.0,766.0,632.0,297.0
Sevilla,831.0,541.0,NaN,646.0,158.0,433.0,703.0,495.0,121.0,486.0,588.0,685.0,824.0
Zaragoza,256.0,246.0,646.0,NaN,628.0,408.0,246.0,368.0,535.0,320.0,652.0,444.0,250.0
Málaga,770.0,468.0,158.0,628.0,NaN,323.0,739.0,391.0,133.0,549.0,716.0,766.0,763.0
Murcia,471.0,177.0,433.0,408.0,323.0,NaN,606.0,69.0,320.0,510.0,800.0,726.0,465.0
Bilbao,469.0,473.0,703.0,246.0,739.0,606.0,NaN,583.0,618.0,232.0,486.0,223.0,465.0
Alicante,407.0,125.0,495.0,368.0,391.0,69.0,583.0,NaN,379.0,515.0,821.0,722.0,401.0
Córdoba,711.0,421.0,121.0,535.0,133.0,320.0,618.0,379.0,NaN,419.0,589.0,634.0,704.0
Valladolid,576.0,441.0,486.0,320.0,549.0,510.0,232.0,515.0,419.0,NaN,337.0,224.0,570.0
Vigo,908.0,766.0,588.0,652.0,716.0,800.0,486.0,821.0,589.0,337.0,NaN,289.0,902.0
Gijón,686.0,632.0,685.0,444.0,766.0,726.0,223.0,722.0,634.0,224.0,289.0,NaN,681.0
Hospitalet de Llobregat,7.0,297.0,824.0,250.0,763.0,465.0,465.0,401.0,704.0,570.0,902.0,681.0,NaN

In [ ]:
#Crear una función que toma como argumentos el nombre de una ciudad, y un DF con la matriz de distancias entre ciudades
# y retorne la ruta mas corta y la cantidad de kms recorridos

def viajar(ciudad_inicio, df):
    ciudad_actual = ciudad_inicio
    ciudades = list(df_distancies_idx.columns)
    #Convertir a un conjunto el nombre de las ciudades para poder iterar sobre ellas
    ciudades_por_visitar = set(ciudades)
    #Remmover del conjunto de ciudades, la indicada como ciudad de inicio para que no la contabilice en el bucle
    ciudades_por_visitar.remove(ciudad_actual)
    #Crear una lista con el nombre de la ciudad de inicio, para ir agregando el resto de ciudades de la ruta 
    ruta = [ciudad_actual]
    #Crear un contador a 0, para contabilizar las distancias en Kms
    distancia_total = 0
    #Crear un bucle while con la condición de que recorra todas las ciudades por visitar
    while ciudades_por_visitar:
        distancia_actual = df.loc[:,ciudad_actual]
        distancia_filtrada = distancia_actual[list(ciudades_por_visitar)]
        #Encontrar de las distancias filtradas el valor mínimo mas cercano
        try:
            ciudad_siguiente = distancia_filtrada.idxmin()
            distancia_recorrida = distancia_filtrada.min()
        except ValueError:
            # Esto debería ocurrir solo si quedan 0 ciudades_por_visitar
            break
        #Actualizar el listado de la ruta con la siguiente ciudad tras el primer bucle, y sumamos la distancia al contador
        ruta.append(ciudad_siguiente)
        distancia_total += distancia_recorrida
        #Remover del listado de ciudades por visitar, la que ya agregamos al listado de la ruta, para actualizar la lista
        ciudades_por_visitar.remove(ciudad_siguiente)
        #Actualizar la ciudad actual, con el nombre de la siguiente ciudad a recorrer por el bucle, por distancia más cercana
        ciudad_actual = ciudad_siguiente
    #Regresar a la ciudad de origen para cerrar el ciclo
    ciudad_origen = ruta[0]
    distancia_regreso = df.loc[ciudad_actual, ciudad_origen]
    ruta.append(ciudad_origen)
    distancia_total += distancia_regreso
    return ruta, distancia_total


#Input por el usuario de la ciudad de inicio de su viaje
origen = str(input('Ingrese la ciudad de origen de su ruta')).capitalize()

#Llamar a la función con los parametros requeridos
ruta_sugerida, distancia_total = viajar(origen, df_distancies_idx)

print(f"Partiendo desde", origen, "la mejor ruta para viajar es:", ruta_sugerida, "\n","La distancia total recorrida es de:", distancia_total, "kms")

data = {'inicio': [origen],'ruta': [ruta_sugerida],"distancia":[distancia_total]}
df_rutas = pd.DataFrame(data)
df_rutas

Partiendo desde Barcelona la mejor ruta para viajar es: ['Barcelona', 'Hospitalet de Llobregat', 'Zaragoza', 'Valencia', 'Alicante', 'Murcia', 'Córdoba', 'Sevilla', 'Málaga', 'Valladolid', 'Gijón', 'Bilbao', 'Vigo', 'Barcelona']
 La distancia total recorrida es de: 3686.0 kms

      inicio                                               ruta  distancia
0  Barcelona  [Barcelona, Hospitalet de Llobregat, Zaragoza,...     3686.0

In [23]:

# Crear una lista vacía, para alojar las posibles rutas
mejores_rutas = []

# Crear la variable ciudades_inicio con los nombres de las columnas del DF
ciudades_inicio = df_distancies_idx.columns

#Iterar con un bucle for sobre todas las ciudades de inicio posibles para encontrar la mejor ruta
for ciudad in ciudades_inicio:
    ruta, distancia = viajar(ciudad, df_distancies_idx)
    #Anexar en la lista mejores_rutas, las tres variables ciudad, ruta, distancia
    mejores_rutas.append({
        'inicio': ciudad,
        'ruta': ruta,
        'distancia': distancia
    })

#Encontrar la ruta con la menor distancia total
df_resultados = pd.DataFrame(mejores_rutas)
mejor_ruta = df_resultados.loc[df_resultados['distancia'].idxmin()]

# Mostrar el Resultado Final 
print(f"La ruta mas corta para visitar las principales ciudades de España, es partiendo desde", mejor_ruta['inicio'],"\n" "con una distancia total recorrida de:", mejor_ruta['distancia'], "kms")
df_resultados

La ruta mas corta para visitar las principales ciudades de España, es partiendo desde Alicante
con una distancia total recorrida de: 3541.0 kms

,inicio,ruta,distancia
0,Barcelona,"[Barcelona, Hospitalet de Llobregat, Zaragoza,...",3686.0
1,Valencia,"[Valencia, Alicante, Murcia, Córdoba, Sevilla,...",3966.0
2,Sevilla,"[Sevilla, Córdoba, Málaga, Murcia, Alicante, V...",3787.0
3,Zaragoza,"[Zaragoza, Valencia, Alicante, Murcia, Córdoba...",4067.0
4,Málaga,"[Málaga, Córdoba, Sevilla, Murcia, Alicante, V...",3836.0
5,Murcia,"[Murcia, Alicante, Valencia, Zaragoza, Bilbao,...",3553.0
6,Bilbao,"[Bilbao, Gijón, Valladolid, Zaragoza, Valencia...",3900.0
7,Alicante,"[Alicante, Murcia, Valencia, Zaragoza, Bilbao,...",3541.0
8,Córdoba,"[Córdoba, Sevilla, Málaga, Murcia, Alicante, V...",3692.0
9,Valladolid,"[Valladolid, Gijón, Bilbao, Zaragoza, Valencia...",3933.0
10,Vigo,"[Vigo, Gijón, Bilbao, Valladolid, Zaragoza, Va...",3781.0
11,Gijón,"[Gijón, Bilbao, Valladolid, Zaragoza, Valencia...",4125.0
12,Hospitalet de Llobregat,"[Hospitalet de Llobregat, Barcelona, Zaragoza,...",3686.0